// Code generated by tools/config-schema-generator. DO NOT EDIT.

package configui

import "github.com/grovetools/core/config"

// SchemaFields contains all config fields sorted by priority.
var SchemaFields = []FieldMeta{
	{
		Path:        []string{"groves"},
		Type:        FieldMap,
		Description: "Root directories to search for projects and ecosystems",
		Layer:       config.SourceGlobal,
		Priority:    1,
		Important:   true,
	},
	{
		Path:        []string{"notebooks"},
		Type:        FieldObject,
		Description: "Notebook configuration",
		Layer:       config.SourceGlobal,
		Priority:    2,
		Important:   true,
		RefType:     "NotebooksConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"notebooks", "definitions"},
				Type:        FieldMap,
				Description: "Map of notebook name to notebook configuration",
			},
			{
				Path:        []string{"notebooks", "rules"},
				Type:        FieldObject,
				Description: "Rules for notebook usage (default notebook",
				RefType:     "NotebookRules",
				Children: []FieldMeta{
					{
						Path:        []string{"notebooks", "rules", "default"},
						Type:        FieldString,
						Description: "Name of the default notebook to use",
						Important:   true,
					},
					{
						Path:        []string{"notebooks", "rules", "global"},
						Type:        FieldObject,
						Description: "Configuration for the system-wide global notebook",
						Important:   true,
						RefType:     "GlobalNotebookConfig",
						Children: []FieldMeta{
							{
								Path:        []string{"notebooks", "rules", "global", "root_dir"},
								Type:        FieldString,
								Description: "Absolute path to the global notebook root directory",
								Important:   true,
								Required:    true,
							},
						},
					},
				},
			},
		},
	},
	{
		Path:        []string{"explicit_projects"},
		Type:        FieldArray,
		Description: "Specific projects to include without discovery",
		Layer:       config.SourceGlobal,
		Priority:    5,
	},
	{
		Path:        []string{"name"},
		Type:        FieldString,
		Description: "Name of the project or ecosystem",
		Layer:       config.SourceEcosystem,
		Priority:    10,
	},
	{
		Path:        []string{"workspaces"},
		Type:        FieldArray,
		Description: "Glob patterns for workspace directories in this ecosystem",
		Layer:       config.SourceEcosystem,
		Priority:    11,
	},
	{
		Path:        []string{"build_cmd"},
		Type:        FieldString,
		Description: "Custom build command (default: make build)",
		Layer:       config.SourceProject,
		Priority:    20,
	},
	{
		Path:        []string{"build_after"},
		Type:        FieldArray,
		Description: "Projects that must be built before this one",
		Layer:       config.SourceProject,
		Priority:    21,
	},
	{
		Path:        []string{"tui"},
		Type:        FieldObject,
		Description: "TUI appearance and behavior settings",
		Layer:       config.SourceGlobal,
		Priority:    50,
		RefType:     "TUISchemaConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"tui", "icons"},
				Type:        FieldSelect,
				Description: "Icon set to use: nerd or ascii",
				Options:     []string{"nerd", "ascii"},
				Important:   true,
			},
			{
				Path:        []string{"tui", "keybindings"},
				Type:        FieldObject,
				Description: "Custom keybinding overrides",
				RefType:     "KeybindingsSchemaConfig",
				Children: []FieldMeta{
					{
						Path:        []string{"tui", "keybindings", "actions"},
						Type:        FieldString,
						Description: "Action keybindings (confirm",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "fold"},
						Type:        FieldString,
						Description: "Fold keybindings (open",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "navigation"},
						Type:        FieldString,
						Description: "Navigation keybindings (up",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "overrides"},
						Type:        FieldMap,
						Description: "Per-TUI keybinding overrides (e.g.",
					},
					{
						Path:        []string{"tui", "keybindings", "search"},
						Type:        FieldString,
						Description: "Search keybindings (search",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "selection"},
						Type:        FieldString,
						Description: "Selection keybindings (select",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "system"},
						Type:        FieldString,
						Description: "System keybindings (quit",
						RefType:     "KeybindingSectionSchemaConfig",
					},
					{
						Path:        []string{"tui", "keybindings", "view"},
						Type:        FieldString,
						Description: "View keybindings (switch_view",
						RefType:     "KeybindingSectionSchemaConfig",
					},
				},
			},
			{
				Path:        []string{"tui", "nvim_embed"},
				Type:        FieldObject,
				Description: "Embedded Neovim configuration",
				RefType:     "NvimEmbedConfig",
				Children: []FieldMeta{
					{
						Path:        []string{"tui", "nvim_embed", "user_config"},
						Type:        FieldBool,
						Description: "If true",
						Required:    true,
					},
				},
			},
			{
				Path:        []string{"tui", "preset"},
				Type:        FieldSelect,
				Description: "Keybinding preset: vim (default) emacs or arrows",
				Options:     []string{"vim", "emacs", "arrows"},
				Important:   true,
			},
			{
				Path:        []string{"tui", "theme"},
				Type:        FieldSelect,
				Description: "Color theme for terminal interfaces",
				Options:     []string{"kanagawa", "gruvbox", "terminal"},
				Important:   true,
			},
		},
	},
	{
		Path:        []string{"logging"},
		Type:        FieldObject,
		Description: "Logging configuration",
		Layer:       config.SourceGlobal,
		Priority:    60,
		RefType:     "LoggingSchemaConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"logging", "log_startup"},
				Type:        FieldBool,
				Description: "Log 'Grove binary started' on first init",
				Required:    true,
			},
			{
				Path:        []string{"logging", "report_caller"},
				Type:        FieldBool,
				Description: "Include file/line/function in output",
				Required:    true,
			},
			{
				Path:        []string{"logging", "show_current_project"},
				Type:        FieldBool,
				Description: "Always show logs from current project regardless of filters",
			},
			{
				Path:        []string{"logging", "groups"},
				Type:        FieldMap,
				Description: "Named collections of component loggers for filtering",
			},
			{
				Path:        []string{"logging", "level"},
				Type:        FieldString,
				Description: "Minimum log level (debug",
				Required:    true,
			},
		},
	},
	{
		Path:        []string{"api_key_command"},
		Type:        FieldString,
		Description: "Shell command to retrieve API key (e.g. gcloud secrets or 1password)",
		Layer:       config.SourceGlobal,
		Priority:    60,
		Important:   true,
		Namespace:   "gemini",
	},
	{
		Path:        []string{"context"},
		Type:        FieldObject,
		Description: "Configuration for the cx (context) tool",
		Layer:       config.SourceGlobal,
		Priority:    80,
		RefType:     "ContextConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"context", "repos_dir"},
				Type:        FieldString,
				Description: "Directory where cx repo stores bare repositories (default: ~/.grove/cx)",
				Layer:       config.SourceGlobal,
				Priority:    80,
			},
			{
				Path:        []string{"context", "default_rules_path"},
				Type:        FieldString,
				Description: "Default rules file path for context filtering",
				Layer:       config.SourceProject,
				Priority:    81,
			},
		},
	},
	{
		Path:        []string{"version"},
		Type:        FieldString,
		Description: "Configuration version (e.g. 1.0)",
		Layer:       config.SourceGlobal,
		Priority:    100,
	},
	{
		Path:        []string{"api_key"},
		Type:        FieldString,
		Description: "Direct API key for Google Gemini",
		Layer:       config.SourceGlobal,
		Priority:    200,
		Sensitive:   true,
		Important:   true,
		Hint:        "Consider using api_key_command to fetch from a secrets manager",
		Namespace:   "gemini",
	},
	{
		Path:             []string{"search_paths"},
		Type:             FieldMap,
		Description:      "DEPRECATED: Use groves instead",
		Layer:            config.SourceGlobal,
		Priority:         1000,
		Status:           StatusDeprecated,
		StatusMessage:    "Use 'groves' for project discovery",
		StatusSince:      "v0.5.0",
		StatusTarget:     "v1.0.0",
		StatusReplacedBy: "groves",
	},
}

// FieldsByPath provides O(1) lookup by full path.
var FieldsByPath = map[string]*FieldMeta{
	"groves":                 &SchemaFields[0],
	"notebooks":              &SchemaFields[1],
	"explicit_projects":      &SchemaFields[2],
	"name":                   &SchemaFields[3],
	"workspaces":             &SchemaFields[4],
	"build_cmd":              &SchemaFields[5],
	"build_after":            &SchemaFields[6],
	"tui":                    &SchemaFields[7],
	"logging":                &SchemaFields[8],
	"gemini.api_key_command": &SchemaFields[9],
	"context":                &SchemaFields[10],
	"version":                &SchemaFields[11],
	"gemini.api_key":         &SchemaFields[12],
	"search_paths":           &SchemaFields[13],
}

// ImportantFields contains only fields marked as important/key configuration options.
var ImportantFields = []*FieldMeta{
	&SchemaFields[0],
	&SchemaFields[1],
	&SchemaFields[9],
	&SchemaFields[12],
}
