// Code generated by tools/config-schema-generator. DO NOT EDIT.

package configui

import "github.com/grovetools/core/config"

// SchemaFields contains all config fields sorted by priority.
var SchemaFields = []FieldMeta{
	{
		Path:        []string{"groves"},
		Type:        FieldMap,
		Description: "Root directories to search for projects and ecosystems",
		Layer:       config.SourceGlobal,
		Priority:    1,
		Wizard:      true,
	},
	{
		Path:        []string{"notebooks"},
		Type:        FieldObject,
		Description: "Notebook configuration",
		Layer:       config.SourceGlobal,
		Priority:    2,
		Wizard:      true,
		RefType:     "NotebooksConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"notebooks", "definitions"},
				Type:        FieldMap,
				Description: "Map of notebook name to notebook configuration",
			},
			{
				Path:        []string{"notebooks", "rules"},
				Type:        FieldObject,
				Description: "Rules for notebook usage (default notebook",
				RefType:     "NotebookRules",
				Children: []FieldMeta{
					{
						Path:        []string{"notebooks", "rules", "default"},
						Type:        FieldString,
						Description: "Name of the default notebook to use",
					},
					{
						Path:        []string{"notebooks", "rules", "global"},
						Type:        FieldObject,
						Description: "Configuration for the system-wide global notebook",
						RefType:     "GlobalNotebookConfig",
						Children: []FieldMeta{
							{
								Path:        []string{"notebooks", "rules", "global", "root_dir"},
								Type:        FieldString,
								Description: "Absolute path to the global notebook root directory",
								Required:    true,
							},
						},
					},
				},
			},
		},
	},
	{
		Path:        []string{"explicit_projects"},
		Type:        FieldArray,
		Description: "Specific projects to include without discovery",
		Layer:       config.SourceGlobal,
		Priority:    5,
	},
	{
		Path:        []string{"name"},
		Type:        FieldString,
		Description: "Name of the project or ecosystem",
		Layer:       config.SourceEcosystem,
		Priority:    10,
	},
	{
		Path:        []string{"workspaces"},
		Type:        FieldArray,
		Description: "Glob patterns for workspace directories in this ecosystem",
		Layer:       config.SourceEcosystem,
		Priority:    11,
	},
	{
		Path:        []string{"build_cmd"},
		Type:        FieldString,
		Description: "Custom build command (default: make build)",
		Layer:       config.SourceProject,
		Priority:    20,
	},
	{
		Path:        []string{"build_after"},
		Type:        FieldArray,
		Description: "Projects that must be built before this one",
		Layer:       config.SourceProject,
		Priority:    21,
	},
	{
		Path:        []string{"tui"},
		Type:        FieldObject,
		Description: "TUI appearance and behavior settings",
		Layer:       config.SourceGlobal,
		Priority:    50,
		RefType:     "TUIConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"tui", "theme"},
				Type:        FieldSelect,
				Description: "Color theme for terminal interfaces",
				Options:     []string{"kanagawa", "gruvbox", "terminal"},
				Layer:       config.SourceGlobal,
				Priority:    51,
			},
			{
				Path:        []string{"tui", "icons"},
				Type:        FieldSelect,
				Description: "Icon set to use: nerd or ascii",
				Options:     []string{"nerd", "ascii"},
				Layer:       config.SourceGlobal,
				Priority:    52,
			},
			{
				Path:          []string{"tui", "nvim_embed"},
				Type:          FieldObject,
				Description:   "Embedded Neovim configuration",
				Layer:         config.SourceGlobal,
				Priority:      53,
				RefType:       "NvimEmbedConfig",
				Status:        StatusAlpha,
				StatusMessage: "Experimental Neovim embedding",
				StatusSince:   "v0.6.0",
				StatusTarget:  "v1.0",
				Children: []FieldMeta{
					{
						Path:        []string{"tui", "nvim_embed", "user_config"},
						Type:        FieldBool,
						Description: "If true",
						Required:    true,
					},
				},
			},
		},
	},
	{
		Path:        []string{"api_key_command"},
		Type:        FieldString,
		Description: "Shell command to retrieve API key (e.g. gcloud secrets or 1password)",
		Layer:       config.SourceGlobal,
		Priority:    60,
		Namespace:   "gemini",
	},
	{
		Path:        []string{"available_keys"},
		Type:        FieldArray,
		Description: "Keys available for tmux pane shortcuts",
		Layer:       config.SourceGlobal,
		Priority:    70,
		Namespace:   "tmux",
	},
	{
		Path:        []string{"show_child_processes"},
		Type:        FieldBool,
		Description: "Show child processes in pane list",
		Layer:       config.SourceGlobal,
		Priority:    71,
		Namespace:   "tmux",
	},
	{
		Path:        []string{"context"},
		Type:        FieldObject,
		Description: "Configuration for the cx (context) tool",
		Layer:       config.SourceGlobal,
		Priority:    80,
		RefType:     "ContextConfig",
		Children: []FieldMeta{
			{
				Path:        []string{"context", "repos_dir"},
				Type:        FieldString,
				Description: "Directory where cx repo stores bare repositories (default: ~/.grove/cx)",
				Layer:       config.SourceGlobal,
				Priority:    80,
			},
			{
				Path:        []string{"context", "default_rules_path"},
				Type:        FieldString,
				Description: "Default rules file path for context filtering",
				Layer:       config.SourceProject,
				Priority:    81,
			},
		},
	},
	{
		Path:        []string{"version"},
		Type:        FieldString,
		Description: "Configuration version (e.g. 1.0)",
		Layer:       config.SourceGlobal,
		Priority:    100,
	},
	{
		Path:        []string{"api_key"},
		Type:        FieldString,
		Description: "Direct API key for Google Gemini",
		Layer:       config.SourceGlobal,
		Priority:    200,
		Sensitive:   true,
		Hint:        "Consider using api_key_command to fetch from a secrets manager",
		Namespace:   "gemini",
	},
	{
		Path:             []string{"search_paths"},
		Type:             FieldMap,
		Description:      "DEPRECATED: Use groves instead",
		Layer:            config.SourceGlobal,
		Priority:         1000,
		Status:           StatusDeprecated,
		StatusMessage:    "Use 'groves' for project discovery",
		StatusSince:      "v0.5.0",
		StatusTarget:     "v1.0.0",
		StatusReplacedBy: "groves",
	},
}

// FieldsByPath provides O(1) lookup by full path.
var FieldsByPath = map[string]*FieldMeta{
	"groves":                    &SchemaFields[0],
	"notebooks":                 &SchemaFields[1],
	"explicit_projects":         &SchemaFields[2],
	"name":                      &SchemaFields[3],
	"workspaces":                &SchemaFields[4],
	"build_cmd":                 &SchemaFields[5],
	"build_after":               &SchemaFields[6],
	"tui":                       &SchemaFields[7],
	"gemini.api_key_command":    &SchemaFields[8],
	"tmux.available_keys":       &SchemaFields[9],
	"tmux.show_child_processes": &SchemaFields[10],
	"context":                   &SchemaFields[11],
	"version":                   &SchemaFields[12],
	"gemini.api_key":            &SchemaFields[13],
	"search_paths":              &SchemaFields[14],
}

// WizardFields contains only fields marked for the setup wizard.
var WizardFields = []*FieldMeta{
	&SchemaFields[0],
	&SchemaFields[1],
}
