// Code generated by tools/registry-generator. DO NOT EDIT.

package sdk

var toolRegistry = map[string]ToolInfo{
	"agentlogs":       {Alias: "aglogs", Description: "Agent transcript log parsing and monitoring"},
	"core":            {Alias: "core", Description: "Core libraries and debugging tools for the Grove ecosystem"},
	"cx":              {Alias: "cx", Description: "LLM context management"},
	"docgen":          {Alias: "docgen", Description: "LLM-powered, workspace-aware documentation generator."},
	"flow":            {Alias: "flow", Description: "Job orchestration and workflows"},
	"grove":           {Alias: "grove", Description: "Grove package manager and command delegator"},
	"grove-anthropic": {Alias: "grove-anthropic", Description: "Tools for using Anthropic/Claude API plaform"},
	"grove-gemini":    {Alias: "grove-gemini", Description: "Tools for Google's Gemini API"},
	"grove.nvim":      {Alias: "grove-nvim", Description: "Neovim plugin for grove"},
	"hooks":           {Alias: "hooks", Description: "Claude hooks integration for Grove ecosystem"},
	"nav":             {Alias: "nav", Description: "Tmux session management for Grove ecosystem"},
	"nb":              {Alias: "nb", Description: "Notebook and documentation management"},
	"notify":          {Alias: "notify", Description: "Notification system for Grove ecosystem"},
	"skills":          {Alias: "skills", Description: "Agent Skill Integrations"},
	"tend":            {Alias: "tend", Description: "Scenario-based testing"},
}
