// Code generated by tools/registry-generator. DO NOT EDIT.

package sdk

var toolRegistry = map[string]ToolInfo{
	"grove-agent-logs":    {Alias: "aglogs", Description: "Agent transcript log parsing and monitoring"},
	"grove-anthropic":     {Alias: "grove-anthropic", Description: "Tools for using Anthropic/Claude API plaform"},
	"grove-context":       {Alias: "cx", Description: "LLM context management"},
	"grove-core":          {Alias: "core", Description: "Core libraries and debugging tools for the Grove ecosystem"},
	"grove-docgen":        {Alias: "docgen", Description: "LLM-powered, workspace-aware documentation generator."},
	"grove-flow":          {Alias: "flow", Description: "Job orchestration and workflows"},
	"grove-gemini":        {Alias: "gemapi", Description: "Tools for Google's Gemini API"},
	"grove-hooks":         {Alias: "grove-hooks", Description: "Claude hooks integration for Grove ecosystem"},
	"grove-meta":          {Alias: "grove", Description: "Grove package manager and command delegator"},
	"grove-notebook":      {Alias: "nb", Description: "Notebook and documentation management"},
	"grove-notifications": {Alias: "notify", Description: "Notification system for Grove ecosystem"},
	"grove-nvim":          {Alias: "neogrove", Description: "Neovim plugin for grove"},
	"grove-skills":        {Alias: "grove-skills", Description: "Agent Skill Integrations"},
	"grove-tend":          {Alias: "tend", Description: "Scenario-based testing"},
	"grove-tmux":          {Alias: "gmux", Description: "Tmux session management for Grove ecosystem"},
}
