// Code generated by tools/registry-generator. DO NOT EDIT.

package sdk

var toolRegistry = map[string]ToolInfo{
	"grove-agent-logs":    {Alias: "aglogs"},
	"grove-anthropic":     {Alias: "grove-anthropic"},
	"grove-context":       {Alias: "cx"},
	"grove-core":          {Alias: "core"},
	"grove-docgen":        {Alias: "docgen"},
	"grove-flow":          {Alias: "flow"},
	"grove-gemini":        {Alias: "gemapi"},
	"grove-hooks":         {Alias: "grove-hooks"},
	"grove-meta":          {Alias: "grove"},
	"grove-notebook":      {Alias: "nb"},
	"grove-notifications": {Alias: "notify"},
	"grove-nvim":          {Alias: "neogrove"},
	"grove-skills":        {Alias: "grove-skills"},
	"grove-tend":          {Alias: "tend"},
	"grove-tmux":          {Alias: "gmux"},
}
