# Generated by `grove forge` from [forge.infra] and [forge.services].
# Edit the config, not this file: every forge verb rewrites it before
# running terraform, and `grove forge down` relies on it to destroy
# without prompting.

# --- machine ---
project_id    = "example-project"
zone          = "us-east1-b"
vm_name       = "grove-forge"
machine_type  = "e2-medium"
disk_size_gb  = 50
image_family  = "debian-12"
image_project = "debian-cloud"

# --- access (an operator CIDR; the open internet is refused) ---
ssh_user       = "grovedev"
allowed_cidr   = "203.0.113.7/32"
enable_iap_ssh = true

# --- identity ---
# Empty means the module creates a dedicated service account with no IAM
# roles and attaches it with no OAuth scopes.
service_account_email = ""

# --- services ---
domain   = ""
tls_mode = "self-signed"
forgejo_version   = "16.0.2"
forgejo_sha256    = "9f2c1b7d4e6a8c0f3b5d7e9a1c3e5f7092b4d6f8a0c2e4f68a9b1d3f5e7a9c1b"
forgejo_http_port = 3000
forgejo_site_name = "grove forge"
syncd_enabled     = true
syncd_port        = 8788
