# Generated by `grove forge` from [forge.infra] and [forge.services].
# Edit the config, not this file: every forge verb rewrites it before
# running terraform, and `grove forge down` relies on it to destroy
# without prompting.

# --- machine ---
project_id    = "example-project"
zone          = "us-central1-a"
vm_name       = "grove-forge-prod"
machine_type  = "e2-standard-2"
disk_size_gb  = 200
image_family  = "debian-12"
image_project = "debian-cloud"

# --- access (an operator CIDR; the open internet is refused) ---
ssh_user       = "grovedev"
allowed_cidr   = "203.0.113.7/32"
enable_iap_ssh          = true
ssh_ingress            = "iap"
syncd_ingress_enabled  = false
forgejo_ingress_enabled = false
ssh_pubkey_file = "~/.ssh/forge.pub"

# --- identity ---
# Empty means the module creates a dedicated service account with no IAM
# roles and attaches it with no OAuth scopes.
service_account_email = "forge@example-project.iam.gserviceaccount.com"

# --- services ---
domain   = "forge.example.com"
tls_mode = "acme"
acme_email        = "ops@example.com"
acme_dns_provider = "cloudflare"
forgejo_version   = "16.0.2"
forgejo_sha256    = "9f2c1b7d4e6a8c0f3b5d7e9a1c3e5f7092b4d6f8a0c2e4f68a9b1d3f5e7a9c1b"
forgejo_http_port = 3080
forgejo_site_name = "solar forge"
syncd_enabled     = true
syncd_port        = 9788

# --- backup ---
backup_enabled = true
backup_bucket          = "example-project-grove-forge-backups"
backup_create_bucket   = true
backup_location        = "us-central1"
backup_retention_days  = 365
backup_nearline_days   = 14
backup_noncurrent_days = 45
