# grove-syncd install fragment, rendered by terraform and injected into the VM
# startup script. Runs as root under `set -euxo pipefail`.
#
# It never downloads a binary: `grove forge up --prebuilt` ships one built on
# the laptop. Everything here is idempotent so a reboot or a re-apply is a
# no-op.

echo "--- grove-syncd (port ${port}, tls ${tls_mode}) ---"

getent group ${tls_group} >/dev/null || groupadd --system ${tls_group}

install -d -m 0750 /var/lib/grove-syncd
install -d -m 0750 /var/log/grove-syncd

%{ if tls_mode == "acme" ~}
# ACME via lego, DNS-01 ONLY. HTTP-01 is deliberately not offered: it needs
# inbound :80 from the world, and no rule in this module may open a port to the
# internet. The DNS provider's credentials are read from
# /etc/grove-forge/acme.env, which the operator installs out of band — never
# from terraform state and never from instance metadata.
if ! command -v lego >/dev/null 2>&1; then
  LEGO_TARBALL=lego_v4.17.4_linux_amd64.tar.gz
  curl -fsSL "https://github.com/go-acme/lego/releases/download/v4.17.4/$LEGO_TARBALL" -o /tmp/lego.tgz
  tar -C /usr/local/bin -xzf /tmp/lego.tgz lego
  rm -f /tmp/lego.tgz
fi
if [ ! -f /etc/grove-forge/acme.env ]; then
  echo "grove forge: tls_mode=acme but /etc/grove-forge/acme.env is missing" >&2
  echo "grove forge: install the DNS provider credentials, then: systemctl start grove-forge-acme" >&2
fi
cat > /usr/local/sbin/grove-forge-acme <<'ACME_RENEW'
#!/bin/sh
set -eu
. /etc/grove-forge/acme.env
lego --accept-tos --email "$ACME_EMAIL" --dns "$ACME_DNS_PROVIDER" \
  --domains "$ACME_DOMAIN" --path /var/lib/grove-forge/acme run || \
lego --accept-tos --email "$ACME_EMAIL" --dns "$ACME_DNS_PROVIDER" \
  --domains "$ACME_DOMAIN" --path /var/lib/grove-forge/acme renew
install -m 0644 -o root -g root \
  "/var/lib/grove-forge/acme/certificates/$ACME_DOMAIN.crt" /etc/grove-forge/tls/cert.pem
install -m 0640 -o root -g ${tls_group} \
  "/var/lib/grove-forge/acme/certificates/$ACME_DOMAIN.key" /etc/grove-forge/tls/key.pem
systemctl reload-or-restart grove-syncd.service || true
ACME_RENEW
chmod 0700 /usr/local/sbin/grove-forge-acme

cat > /etc/grove-forge/acme.defaults <<ACME_DEFAULTS
ACME_EMAIL=${acme_email}
ACME_DNS_PROVIDER=${acme_dns_provider}
ACME_DOMAIN=${domain}
ACME_DEFAULTS
chmod 0644 /etc/grove-forge/acme.defaults

cat > /etc/systemd/system/grove-forge-acme.service <<'ACME_UNIT'
[Unit]
Description=Obtain/renew the grove forge certificate via ACME DNS-01
[Service]
Type=oneshot
ExecStart=/usr/local/sbin/grove-forge-acme
ACME_UNIT

cat > /etc/systemd/system/grove-forge-acme.timer <<'ACME_TIMER'
[Unit]
Description=Daily ACME renewal check for the grove forge certificate
[Timer]
OnCalendar=daily
RandomizedDelaySec=6h
Persistent=true
[Install]
WantedBy=timers.target
ACME_TIMER
systemctl daemon-reload
systemctl enable grove-forge-acme.timer
%{ else ~}
# Self-signed: the certificate was generated by the caller's TLS section. Hand
# the private key to the service's group so DynamicUser can read it, and keep
# it unreadable by anyone else.
if [ -f /etc/grove-forge/tls/key.pem ]; then
  chown root:${tls_group} /etc/grove-forge/tls/key.pem
  chmod 0640 /etc/grove-forge/tls/key.pem
fi
%{ endif ~}

cat > /etc/systemd/system/grove-syncd.service <<'SYNCD_UNIT'
${unit}
SYNCD_UNIT

systemctl daemon-reload
systemctl enable grove-syncd.service
# Enabled, not started: the unit's ConditionPathExists holds it until
# `grove forge up --prebuilt` installs /usr/local/bin/grove-syncd.
if [ -x /usr/local/bin/grove-syncd ]; then
  systemctl start grove-syncd.service
else
  echo "grove-syncd not installed yet; the unit is enabled and will start once the binary is shipped"
fi
