// Code generated by keys-registry-generator. DO NOT EDIT.
// Run 'make keys-registry' to regenerate.

package keys

// TUIRegistry contains keybinding information for all TUIs in the ecosystem.
// This is populated at build time by the keys-registry-generator tool.
var TUIRegistry = []TUIRegistryEntry{
	{
		Name:        "core-logs",
		Package:     "core",
		Description: "Aggregated log viewer with filtering and search",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true, ConfigKey: "confirm"},
					{Name: "cancel", Keys: []string{"ctrl+g"}, Description: "cancel", Enabled: true, ConfigKey: "cancel"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true, ConfigKey: "yank"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "cx-rules",
		Package:     "cx",
		Description: "Context rules picker and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
				},
			},
			{
				Name: "Rules",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"enter"}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "load to .grove/rules", Keys: []string{"l"}, Description: "load to .grove/rules", Enabled: true, ConfigKey: "load"},
					{Name: "save", Keys: []string{"s"}, Description: "save", Enabled: true, ConfigKey: "save"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "cx-view",
		Package:     "cx",
		Description: "Context viewer with tree, stats, and list pages",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "go to top", Keys: []string{"g"}, Description: "go to top", Enabled: true, ConfigKey: "goto_top"},
					{Name: "go to bottom", Keys: []string{"G"}, Description: "go to bottom", Enabled: true, ConfigKey: "goto_bottom"},
					{Name: "half page up", Keys: []string{"ctrl+u"}, Description: "half page up", Enabled: true, ConfigKey: "half_page_up"},
					{Name: "half page down", Keys: []string{"ctrl+d"}, Description: "half page down", Enabled: true, ConfigKey: "half_page_down"},
				},
			},
			{
				Name: "Pages",
				Bindings: []BindingEntry{
					{Name: "next page", Keys: []string{"tab"}, Description: "next page", Enabled: true, ConfigKey: "next_page"},
					{Name: "prev page", Keys: []string{"shift+tab"}, Description: "prev page", Enabled: true, ConfigKey: "prev_page"},
				},
			},
			{
				Name: "Rules",
				Bindings: []BindingEntry{
					{Name: "edit rules", Keys: []string{"e"}, Description: "edit rules", Enabled: true, ConfigKey: "edit"},
					{Name: "select rule set", Keys: []string{"s"}, Description: "select rule set", Enabled: true, ConfigKey: "select_rules"},
					{Name: "exclude file", Keys: []string{"x"}, Description: "exclude file", Enabled: true, ConfigKey: "exclude"},
					{Name: "exclude dir", Keys: []string{"X"}, Description: "exclude dir", Enabled: true, ConfigKey: "exclude_dir"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
				},
			},
			{
				Name: "Display",
				Bindings: []BindingEntry{
					{Name: "toggle sort", Keys: []string{"t"}, Description: "toggle sort", Enabled: true, ConfigKey: "toggle_sort"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "flow-plan-add",
		Package:     "flow",
		Description: "Add new job to a plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "next field", Keys: []string{"tab"}, Description: "next field", Enabled: true, ConfigKey: "next"},
					{Name: "prev field", Keys: []string{"shift+tab"}, Description: "prev field", Enabled: true, ConfigKey: "prev"},
					{Name: "go to top", Keys: []string{"gg", "home"}, Description: "go to top", Enabled: true, ConfigKey: "go_top"},
					{Name: "go to bottom", Keys: []string{"G", "end"}, Description: "go to bottom", Enabled: true, ConfigKey: "go_bottom"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "toggle", Keys: []string{" "}, Description: "toggle", Enabled: true, ConfigKey: "toggle"},
					{Name: "submit", Keys: []string{"ctrl+s"}, Description: "submit", Enabled: true, ConfigKey: "submit"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "flow-plan-finish",
		Package:     "flow",
		Description: "Finish and clean up a plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "toggle selection", Keys: []string{" "}, Description: "toggle selection", Enabled: true, ConfigKey: "toggle"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm and proceed", Keys: []string{"enter"}, Description: "confirm and proceed", Enabled: true, ConfigKey: "confirm"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "flow-plan-init",
		Package:     "flow",
		Description: "Create a new plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "next field", Keys: []string{"tab", "j"}, Description: "next field", Enabled: true, ConfigKey: "next_field"},
					{Name: "prev field", Keys: []string{"shift+tab", "k"}, Description: "prev field", Enabled: true, ConfigKey: "prev_field"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "toggle checkbox", Keys: []string{" "}, Description: "toggle checkbox", Enabled: true, ConfigKey: "toggle"},
					{Name: "submit form", Keys: []string{"enter"}, Description: "submit form", Enabled: true, ConfigKey: "submit"},
					{Name: "toggle advanced", Keys: []string{"a"}, Description: "toggle advanced", Enabled: true, ConfigKey: "toggle_advanced"},
					{Name: "insert mode", Keys: []string{"i"}, Description: "insert mode", Enabled: true, ConfigKey: "insert"},
					{Name: "normal mode", Keys: []string{"esc"}, Description: "normal mode", Enabled: true, ConfigKey: "escape"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "show help", Keys: []string{"?"}, Description: "show help", Enabled: true, ConfigKey: "help"},
					{Name: "back to plan list", Keys: []string{"q"}, Description: "back to plan list", Enabled: true, ConfigKey: "back"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "flow-plan-list",
		Package:     "flow",
		Description: "Plan browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "move up", Keys: []string{"k", "up"}, Description: "move up", Enabled: true, ConfigKey: "up"},
					{Name: "move down", Keys: []string{"j", "down"}, Description: "move down", Enabled: true, ConfigKey: "down"},
					{Name: "view plan details", Keys: []string{"enter"}, Description: "view plan details", Enabled: true, ConfigKey: "view_plan"},
					{Name: "open plan workspace", Keys: []string{"o"}, Description: "open plan workspace", Enabled: true, ConfigKey: "open_plan"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "create new plan", Keys: []string{"n"}, Description: "create new plan", Enabled: true, ConfigKey: "new_plan"},
					{Name: "set active plan", Keys: []string{"s"}, Description: "set active plan", Enabled: true, ConfigKey: "set_active"},
					{Name: "edit notes", Keys: []string{"e"}, Description: "edit notes", Enabled: true, ConfigKey: "edit_notes"},
					{Name: "review changes", Keys: []string{"r"}, Description: "review changes", Enabled: true, ConfigKey: "review_plan"},
					{Name: "finish plan", Keys: []string{"ctrl+x"}, Description: "finish plan", Enabled: true, ConfigKey: "finish_plan"},
					{Name: "hold/unhold plan", Keys: []string{"h"}, Description: "hold/unhold plan", Enabled: true, ConfigKey: "set_hold_status"},
					{Name: "update from main", Keys: []string{"U"}, Description: "update from main", Enabled: true, ConfigKey: "fast_forward_update"},
					{Name: "merge to main", Keys: []string{"M"}, Description: "merge to main", Enabled: true, ConfigKey: "fast_forward_main"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle git log", Keys: []string{"g"}, Description: "toggle git log", Enabled: true, ConfigKey: "toggle_git_log"},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true, ConfigKey: "toggle_hold"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "flow-status",
		Package:     "flow",
		Description: "Flow plan status browser and job manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "Views",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "toggle columns", Keys: []string{"T"}, Description: "toggle columns", Enabled: true, ConfigKey: "toggle_columns"},
					{Name: "view logs", Keys: []string{"l"}, Description: "view logs", Enabled: true, ConfigKey: "view_logs"},
					{Name: "view frontmatter", Keys: []string{"f"}, Description: "view frontmatter", Enabled: true, ConfigKey: "view_frontmatter"},
					{Name: "view briefing", Keys: []string{"b"}, Description: "view briefing", Enabled: true, ConfigKey: "view_briefing"},
					{Name: "preview markdown", Keys: []string{"m", "p"}, Description: "preview markdown", Enabled: true, ConfigKey: "view_edit"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
					{Name: "toggle detail pane", Keys: []string{"v"}, Description: "toggle detail pane", Enabled: true, ConfigKey: "cycle_detail_pane"},
					{Name: "close detail pane", Keys: []string{"esc"}, Description: "close detail pane", Enabled: true, ConfigKey: "close_detail_pane"},
					{Name: "switch focus", Keys: []string{"tab", "shift+tab"}, Description: "switch focus", Enabled: true, ConfigKey: "switch_focus"},
					{Name: "toggle layout", Keys: []string{"V"}, Description: "toggle layout", Enabled: true, ConfigKey: "toggle_layout"},
					{Name: "fullscreen logs", Keys: []string{"z"}, Description: "fullscreen logs", Enabled: true, ConfigKey: "toggle_fullscreen"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run job", Keys: []string{"r"}, Description: "run job", Enabled: true, ConfigKey: "run"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "mark completed", Keys: []string{"c"}, Description: "mark completed", Enabled: true, ConfigKey: "set_completed"},
					{Name: "set status", Keys: []string{"S"}, Description: "set status", Enabled: true, ConfigKey: "set_status"},
					{Name: "set type", Keys: []string{"Y"}, Description: "set type", Enabled: true, ConfigKey: "set_type"},
					{Name: "set template", Keys: []string{"E"}, Description: "set template", Enabled: true, ConfigKey: "set_template"},
					{Name: "add job", Keys: []string{"A"}, Description: "add job", Enabled: true, ConfigKey: "add_job"},
					{Name: "add from recipe", Keys: []string{"P"}, Description: "add from recipe", Enabled: true, ConfigKey: "add_from_recipe"},
					{Name: "add XML plan job", Keys: []string{"x"}, Description: "add XML plan job", Enabled: true, ConfigKey: "add_xml_plan"},
					{Name: "implement selected", Keys: []string{"i"}, Description: "implement selected", Enabled: true, ConfigKey: "implement"},
					{Name: "rename job", Keys: []string{"R"}, Description: "rename job", Enabled: true, ConfigKey: "rename"},
					{Name: "resume job", Keys: []string{"ctrl+R"}, Description: "resume job", Enabled: true, ConfigKey: "resume"},
					{Name: "edit dependencies", Keys: []string{"D"}, Description: "edit dependencies", Enabled: true, ConfigKey: "edit_deps"},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true, ConfigKey: "archive"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "gemini-cache",
		Package:     "grove-gemini",
		Description: "Response cache browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true, ConfigKey: "confirm"},
					{Name: "cancel", Keys: []string{"ctrl+g"}, Description: "cancel", Enabled: true, ConfigKey: "cancel"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true, ConfigKey: "yank"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear_search"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
			{
				Name: "Cache Actions",
				Bindings: []BindingEntry{
					{Name: "inspect", Keys: []string{"i", "enter"}, Description: "inspect", Enabled: true, ConfigKey: "inspect"},
					{Name: "analytics", Keys: []string{"a"}, Description: "analytics", Enabled: true, ConfigKey: "analytics"},
					{Name: "delete from API", Keys: []string{"d"}, Description: "delete from API", Enabled: true, ConfigKey: "delete"},
					{Name: "wipe local", Keys: []string{"w"}, Description: "wipe local", Enabled: true, ConfigKey: "wipe"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
				},
			},
		},
	},
	{
		Name:        "gemini-dashboard",
		Package:     "grove-gemini",
		Description: "BigQuery billing dashboard viewer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Time Frame",
				Bindings: []BindingEntry{
					{Name: "daily view", Keys: []string{"d"}, Description: "daily view", Enabled: true, ConfigKey: "daily_view"},
					{Name: "weekly view", Keys: []string{"w"}, Description: "weekly view", Enabled: true, ConfigKey: "weekly_view"},
					{Name: "monthly view", Keys: []string{"m"}, Description: "monthly view", Enabled: true, ConfigKey: "monthly_view"},
					{Name: "90-day view", Keys: []string{"3"}, Description: "90-day view", Enabled: true, ConfigKey: "quarterly_view"},
					{Name: "yearly view", Keys: []string{"y"}, Description: "yearly view", Enabled: true, ConfigKey: "yearly_view"},
				},
			},
			{
				Name: "Period Navigation",
				Bindings: []BindingEntry{
					{Name: "previous period", Keys: []string{"left", "h"}, Description: "previous period", Enabled: true, ConfigKey: "prev_period"},
					{Name: "next period", Keys: []string{"right", "l"}, Description: "next period", Enabled: true, ConfigKey: "next_period"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "gemini-query",
		Package:     "grove-gemini",
		Description: "Query usage analytics and logs viewer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Time Frame",
				Bindings: []BindingEntry{
					{Name: "daily view", Keys: []string{"d"}, Description: "daily view", Enabled: true, ConfigKey: "daily_view"},
					{Name: "weekly view", Keys: []string{"w"}, Description: "weekly view", Enabled: true, ConfigKey: "weekly_view"},
					{Name: "monthly view", Keys: []string{"m"}, Description: "monthly view", Enabled: true, ConfigKey: "monthly_view"},
				},
			},
			{
				Name: "Period Navigation",
				Bindings: []BindingEntry{
					{Name: "previous period", Keys: []string{"left", "h"}, Description: "previous period", Enabled: true, ConfigKey: "prev_period"},
					{Name: "next period", Keys: []string{"right", "l"}, Description: "next period", Enabled: true, ConfigKey: "next_period"},
				},
			},
			{
				Name: "Display",
				Bindings: []BindingEntry{
					{Name: "toggle metric", Keys: []string{"t"}, Description: "toggle metric", Enabled: true, ConfigKey: "toggle_metric"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "grove-config",
		Package:     "grove",
		Description: "Interactive configuration editor",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true, ConfigKey: "confirm"},
					{Name: "cancel", Keys: []string{"ctrl+g"}, Description: "cancel", Enabled: true, ConfigKey: "cancel"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true, ConfigKey: "yank"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear_search"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "grove-keys",
		Package:     "grove",
		Description: "Keybinding browser and analyzer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "toggle view", Keys: []string{"v"}, Description: "toggle view", Enabled: true, ConfigKey: "toggle_view"},
					{Name: "edit config", Keys: []string{"e"}, Description: "edit config", Enabled: true, ConfigKey: "edit_config"},
				},
			},
			{
				Name: "Matrix View",
				Bindings: []BindingEntry{
					{Name: "scroll TUIs left", Keys: []string{"h"}, Description: "scroll TUIs left", Enabled: true, ConfigKey: "scroll_tui_left"},
					{Name: "scroll TUIs right", Keys: []string{"l"}, Description: "scroll TUIs right", Enabled: true, ConfigKey: "scroll_tui_right"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "grove-onboard",
		Package:     "grove",
		Description: "Initial system onboarding wizard",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true, ConfigKey: "confirm"},
					{Name: "cancel", Keys: []string{"ctrl+g"}, Description: "cancel", Enabled: true, ConfigKey: "cancel"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true, ConfigKey: "yank"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear_search"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "grove-release",
		Package:     "grove",
		Description: "Release management with changelog generation",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "tab"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "toggle selection", Keys: []string{" ", "x"}, Description: "toggle selection", Enabled: true, ConfigKey: "toggle"},
					{Name: "select all", Keys: []string{"ctrl+a"}, Description: "select all", Enabled: true, ConfigKey: "select_all"},
					{Name: "deselect all", Keys: []string{"ctrl+d"}, Description: "deselect all", Enabled: true, ConfigKey: "deselect_all"},
				},
			},
			{
				Name: "Version Bumps",
				Bindings: []BindingEntry{
					{Name: "set major", Keys: []string{"m"}, Description: "set major", Enabled: true, ConfigKey: "select_major"},
					{Name: "set minor", Keys: []string{"n"}, Description: "set minor", Enabled: true, ConfigKey: "select_minor"},
					{Name: "set patch", Keys: []string{"p"}, Description: "set patch", Enabled: true, ConfigKey: "select_patch"},
					{Name: "apply suggestion", Keys: []string{"s"}, Description: "apply suggestion", Enabled: true, ConfigKey: "apply_suggestion"},
				},
			},
			{
				Name: "Changelog",
				Bindings: []BindingEntry{
					{Name: "view changelog", Keys: []string{"v"}, Description: "view changelog", Enabled: true, ConfigKey: "view_changelog"},
					{Name: "edit staged changelog", Keys: []string{"e"}, Description: "edit staged changelog", Enabled: true, ConfigKey: "edit_changelog"},
					{Name: "edit repo CHANGELOG.md", Keys: []string{"E"}, Description: "edit repo CHANGELOG.md", Enabled: true, ConfigKey: "edit_repo_changelog"},
					{Name: "generate changelog (LLM)", Keys: []string{"g"}, Description: "generate changelog (LLM)", Enabled: true, ConfigKey: "generate_changelog"},
					{Name: "generate all changelogs", Keys: []string{"G"}, Description: "generate all changelogs", Enabled: true, ConfigKey: "generate_all"},
					{Name: "write changelog to repo", Keys: []string{"w"}, Description: "write changelog to repo", Enabled: true, ConfigKey: "write_changelog"},
				},
			},
			{
				Name: "LLM Rules",
				Bindings: []BindingEntry{
					{Name: "edit LLM rules", Keys: []string{"r"}, Description: "edit LLM rules", Enabled: true, ConfigKey: "edit_rules"},
					{Name: "reset all rules to *", Keys: []string{"R"}, Description: "reset all rules to *", Enabled: true, ConfigKey: "reset_rules"},
				},
			},
			{
				Name: "Settings",
				Bindings: []BindingEntry{
					{Name: "toggle dry-run mode", Keys: []string{"d"}, Description: "toggle dry-run mode", Enabled: true, ConfigKey: "toggle_dry_run"},
					{Name: "toggle push to remote", Keys: []string{"P"}, Description: "toggle push to remote", Enabled: true, ConfigKey: "toggle_push"},
					{Name: "toggle sync dependencies", Keys: []string{"S"}, Description: "toggle sync dependencies", Enabled: true, ConfigKey: "toggle_sync_deps"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "approve", Keys: []string{"a"}, Description: "approve", Enabled: true, ConfigKey: "approve"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "grove-wizard",
		Package:     "grove",
		Description: "Initial setup wizard",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true, ConfigKey: "confirm"},
					{Name: "cancel", Keys: []string{"ctrl+g"}, Description: "cancel", Enabled: true, ConfigKey: "cancel"},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true, ConfigKey: "back"},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true, ConfigKey: "edit"},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true, ConfigKey: "delete"},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true, ConfigKey: "yank"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear_search"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true, ConfigKey: "switch_view"},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true, ConfigKey: "next_tab"},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true, ConfigKey: "prev_tab"},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true, ConfigKey: "toggle_preview"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "hooks-browser",
		Package:     "hooks",
		Description: "Hook session browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "scroll up", Keys: []string{"ctrl+u", "pageup"}, Description: "scroll up", Enabled: true, ConfigKey: "scroll_up"},
					{Name: "scroll down", Keys: []string{"ctrl+d", "pagedown"}, Description: "scroll down", Enabled: true, ConfigKey: "scroll_down"},
					{Name: "go to top", Keys: []string{"g"}, Description: "go to top", Enabled: true, ConfigKey: "go_to_top"},
					{Name: "go to bottom", Keys: []string{"G"}, Description: "go to bottom", Enabled: true, ConfigKey: "go_to_bottom"},
					{Name: "jump", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump", Enabled: true, ConfigKey: "jump_to_workspace"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle view", Keys: []string{"t"}, Description: "toggle view", Enabled: true, ConfigKey: "toggle_view"},
					{Name: "toggle filter view", Keys: []string{"f"}, Description: "toggle filter view", Enabled: true, ConfigKey: "toggle_filter"},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search_filter"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "action", Keys: []string{"e"}, Description: "action", Enabled: true, ConfigKey: "open"},
					{Name: "action", Keys: []string{"o"}, Description: "action", Enabled: true, ConfigKey: "open"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
					{Name: "open dir", Keys: []string{"ctrl+o"}, Description: "open dir", Enabled: true, ConfigKey: "open_dir"},
					{Name: "export json", Keys: []string{"ctrl+j"}, Description: "export json", Enabled: true, ConfigKey: "export_json"},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true, ConfigKey: "archive"},
				},
			},
			{
				Name: "Session",
				Bindings: []BindingEntry{
					{Name: "mark complete", Keys: []string{"c"}, Description: "mark complete", Enabled: true, ConfigKey: "mark_complete"},
					{Name: "kill session", Keys: []string{"ctrl+k"}, Description: "kill session", Enabled: true, ConfigKey: "kill"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "nav-history",
		Package:     "nav",
		Description: "Session history browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "jump to row", Keys: []string{"1-9"}, Description: "jump to row", Enabled: true, ConfigKey: "jump_to_row"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "filter", Keys: []string{"/"}, Description: "filter", Enabled: true, ConfigKey: "filter"},
					{Name: "switch to session", Keys: []string{"o", "enter"}, Description: "switch to session", Enabled: true, ConfigKey: "open"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "nav-manage",
		Package:     "nav",
		Description: "Session hotkey manager",
		Sections: []SectionEntry{
			{
				Name: "Groups",
				Bindings: []BindingEntry{
					{Name: "next group", Keys: []string{"tab"}, Description: "next group", Enabled: true, ConfigKey: "next_group"},
					{Name: "prev group", Keys: []string{"shift+tab"}, Description: "prev group", Enabled: true, ConfigKey: "prev_group"},
				},
			},
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
					{Name: "jump to row", Keys: []string{"1-9"}, Description: "jump to row", Enabled: true, ConfigKey: "jump_to_row"},
					{Name: "switch to session", Keys: []string{"o", "enter"}, Description: "switch to session", Enabled: true, ConfigKey: "open"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "map CWD", Keys: []string{"e"}, Description: "map CWD", Enabled: true, ConfigKey: "edit"},
					{Name: "set key mode", Keys: []string{"h"}, Description: "set key mode", Enabled: true, ConfigKey: "set_key"},
					{Name: "quick toggle", Keys: []string{" "}, Description: "quick toggle", Enabled: true, ConfigKey: "toggle"},
					{Name: "clear mapping", Keys: []string{"d", "delete"}, Description: "clear mapping", Enabled: true, ConfigKey: "delete"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Group Operations",
				Bindings: []BindingEntry{
					{Name: "load group into default", Keys: []string{"L"}, Description: "load group into default", Enabled: true, ConfigKey: "load_default"},
					{Name: "clear group", Keys: []string{"C"}, Description: "clear group", Enabled: true, ConfigKey: "unload_default"},
					{Name: "save to group", Keys: []string{"S"}, Description: "save to group", Enabled: true, ConfigKey: "save_to_group"},
				},
			},
			{
				Name: "Reorder",
				Bindings: []BindingEntry{
					{Name: "enter move mode", Keys: []string{"m"}, Description: "enter move mode", Enabled: true, ConfigKey: "move_mode"},
					{Name: "toggle lock", Keys: []string{"l"}, Description: "toggle lock", Enabled: true, ConfigKey: "lock"},
					{Name: "move row (in move mode)", Keys: []string{"j/k"}, Description: "move row (in move mode)", Enabled: true, ConfigKey: "move_row_(in_move_mode)"},
					{Name: "confirm move", Keys: []string{"enter"}, Description: "confirm move", Enabled: true, ConfigKey: "confirm_move"},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle paths", Keys: []string{"p"}, Description: "toggle paths", Enabled: true, ConfigKey: "toggle_paths"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "nav-sessionize",
		Package:     "nav",
		Description: "Tmux session switcher and workspace browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "select session", Keys: []string{"enter"}, Description: "select session", Enabled: true, ConfigKey: "select_session"},
				},
			},
			{
				Name: "Session",
				Bindings: []BindingEntry{
					{Name: "refresh project list", Keys: []string{"ctrl+r"}, Description: "refresh project list", Enabled: true, ConfigKey: "refresh_projects"},
					{Name: "edit key mapping", Keys: []string{"ctrl+e"}, Description: "edit key mapping", Enabled: true, ConfigKey: "edit_key"},
					{Name: "clear key mapping", Keys: []string{"ctrl+x"}, Description: "clear key mapping", Enabled: true, ConfigKey: "clear_key"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
					{Name: "close session", Keys: []string{"X"}, Description: "close session", Enabled: true, ConfigKey: "close_session"},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus ecosystem", Keys: []string{"@"}, Description: "focus ecosystem", Enabled: true, ConfigKey: "focus_ecosystem"},
					{Name: "clear ecosystem focus", Keys: []string{"ctrl+g"}, Description: "clear ecosystem focus", Enabled: true, ConfigKey: "clear_focus"},
					{Name: "toggle worktrees", Keys: []string{"tab"}, Description: "toggle worktrees", Enabled: true, ConfigKey: "toggle_worktrees"},
					{Name: "filter dirty", Keys: []string{"D"}, Description: "filter dirty", Enabled: true, ConfigKey: "filter_dirty"},
					{Name: "toggle context", Keys: []string{"C"}, Description: "toggle context", Enabled: true, ConfigKey: "toggle_hot_context"},
				},
			},
			{
				Name: "Columns",
				Bindings: []BindingEntry{
					{Name: "toggle cx column", Keys: []string{"c"}, Description: "toggle cx column", Enabled: true, ConfigKey: "toggle_cx"},
					{Name: "toggle git status", Keys: []string{"s"}, Description: "toggle git status", Enabled: true, ConfigKey: "toggle_git_status"},
					{Name: "toggle branch names", Keys: []string{"b"}, Description: "toggle branch names", Enabled: true, ConfigKey: "toggle_branch"},
					{Name: "toggle note counts", Keys: []string{"n"}, Description: "toggle note counts", Enabled: true, ConfigKey: "toggle_note_counts"},
					{Name: "toggle flow plans", Keys: []string{"f"}, Description: "toggle flow plans", Enabled: true, ConfigKey: "toggle_plan_stats"},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true, ConfigKey: "toggle_hold"},
					{Name: "toggle full paths", Keys: []string{"p"}, Description: "toggle full paths", Enabled: true, ConfigKey: "toggle_paths"},
					{Name: "toggle release", Keys: []string{"r"}, Description: "toggle release", Enabled: true, ConfigKey: "toggle_release"},
					{Name: "toggle tool/version", Keys: []string{"y"}, Description: "toggle tool/version", Enabled: true, ConfigKey: "toggle_binary"},
					{Name: "toggle remote", Keys: []string{"l"}, Description: "toggle remote", Enabled: true, ConfigKey: "toggle_link"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "nav-windows",
		Package:     "nav",
		Description: "Tmux window manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "jump to window", Keys: []string{"0-9"}, Description: "jump to window", Enabled: true, ConfigKey: "jump_to_window"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "switch", Keys: []string{"enter"}, Description: "switch", Enabled: true, ConfigKey: "switch"},
					{Name: "filter", Keys: []string{"/"}, Description: "filter", Enabled: true, ConfigKey: "filter"},
					{Name: "rename", Keys: []string{"R"}, Description: "rename", Enabled: true, ConfigKey: "rename"},
					{Name: "close", Keys: []string{"X"}, Description: "close", Enabled: true, ConfigKey: "close"},
				},
			},
			{
				Name: "Reorder",
				Bindings: []BindingEntry{
					{Name: "move window", Keys: []string{"m"}, Description: "move window", Enabled: true, ConfigKey: "move_mode"},
					{Name: "move (in move mode)", Keys: []string{"j/k"}, Description: "move (in move mode)", Enabled: true, ConfigKey: "move_(in_move_mode)"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "nb-browser",
		Package:     "nb",
		Description: "Notebook browser and note manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "left", Keys: []string{"left"}, Description: "left", Enabled: true, ConfigKey: "left"},
					{Name: "right", Keys: []string{"right"}, Description: "right", Enabled: true, ConfigKey: "right"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{" "}, Description: "select", Enabled: true, ConfigKey: "select"},
					{Name: "all", Keys: []string{"ctrl+a"}, Description: "all", Enabled: true, ConfigKey: "select_all"},
					{Name: "none", Keys: []string{"-"}, Description: "none", Enabled: true, ConfigKey: "select_none"},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true, ConfigKey: "search_next"},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true, ConfigKey: "search_prev"},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true, ConfigKey: "clear_search"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus ecosystem", Keys: []string{"@"}, Description: "focus ecosystem", Enabled: true, ConfigKey: "focus_ecosystem"},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true, ConfigKey: "clear_focus"},
					{Name: "focus parent (disabled)", Keys: []string{""}, Description: "focus parent (disabled)", Enabled: true, ConfigKey: "focus_parent"},
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true, ConfigKey: "focus_selected"},
					{Name: "focus recent", Keys: []string{"f"}, Description: "focus recent", Enabled: true, ConfigKey: "focus_recent"},
					{Name: "jump to workspace", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump to workspace", Enabled: true, ConfigKey: "jump_to_workspace"},
				},
			},
			{
				Name: "Filter",
				Bindings: []BindingEntry{
					{Name: "filter by tag", Keys: []string{"&"}, Description: "filter by tag", Enabled: true, ConfigKey: "filter_by_tag"},
					{Name: "git changes", Keys: []string{"<", ">"}, Description: "git changes", Enabled: true, ConfigKey: "toggle_git_changes"},
					{Name: "toggle sort order", Keys: []string{"s"}, Description: "toggle sort order", Enabled: true, ConfigKey: "sort"},
				},
			},
			{
				Name: "Toggle",
				Bindings: []BindingEntry{
					{Name: "toggle archives", Keys: []string{"A"}, Description: "toggle archives", Enabled: true, ConfigKey: "toggle_archives"},
					{Name: "toggle artifacts", Keys: []string{"b"}, Description: "toggle artifacts", Enabled: true, ConfigKey: "toggle_artifacts"},
					{Name: "toggle global", Keys: []string{"~"}, Description: "toggle global", Enabled: true, ConfigKey: "toggle_global"},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true, ConfigKey: "toggle_hold"},
					{Name: "toggle columns", Keys: []string{"V"}, Description: "toggle columns", Enabled: true, ConfigKey: "toggle_columns"},
				},
			},
			{
				Name: "Notes",
				Bindings: []BindingEntry{
					{Name: "create note at cursor", Keys: []string{"n"}, Description: "create note at cursor", Enabled: true, ConfigKey: "create_note"},
					{Name: "inbox note (quick capture)", Keys: []string{"i"}, Description: "inbox note (quick capture)", Enabled: true, ConfigKey: "create_note_inbox"},
					{Name: "global note", Keys: []string{"I"}, Description: "global note", Enabled: true, ConfigKey: "create_note_global"},
					{Name: "promote note to plan", Keys: []string{"P"}, Description: "promote note to plan", Enabled: true, ConfigKey: "create_plan"},
					{Name: "rename note", Keys: []string{"R"}, Description: "rename note", Enabled: true, ConfigKey: "rename"},
				},
			},
			{
				Name: "Clipboard",
				Bindings: []BindingEntry{
					{Name: "cut selected", Keys: []string{"x"}, Description: "cut selected", Enabled: true, ConfigKey: "cut"},
					{Name: "copy selected", Keys: []string{"y", "c"}, Description: "copy selected", Enabled: true, ConfigKey: "copy"},
					{Name: "paste from clipboard", Keys: []string{"p"}, Description: "paste from clipboard", Enabled: true, ConfigKey: "paste"},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true, ConfigKey: "archive"},
					{Name: "copy path", Keys: []string{"ctrl+y"}, Description: "copy path", Enabled: true, ConfigKey: "copy_path"},
				},
			},
			{
				Name: "Git",
				Bindings: []BindingEntry{
					{Name: "toggle git stage", Keys: []string{"-"}, Description: "toggle git stage", Enabled: true, ConfigKey: "git_stage_toggle"},
					{Name: "stage all", Keys: []string{"="}, Description: "stage all", Enabled: true, ConfigKey: "git_stage_all"},
					{Name: "unstage all", Keys: []string{"+"}, Description: "unstage all", Enabled: true, ConfigKey: "git_unstage_all"},
					{Name: "git commit", Keys: []string{"C"}, Description: "git commit", Enabled: true, ConfigKey: "git_commit"},
				},
			},
			{
				Name: "Misc",
				Bindings: []BindingEntry{
					{Name: "toggle preview focus", Keys: []string{"tab"}, Description: "toggle preview focus", Enabled: true, ConfigKey: "preview"},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true, ConfigKey: "refresh"},
					{Name: "sync with remotes", Keys: []string{"S"}, Description: "sync with remotes", Enabled: true, ConfigKey: "sync"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "tend-runner",
		Package:     "tend",
		Description: "Test runner and e2e test browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true, ConfigKey: "top"},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true, ConfigKey: "bottom"},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true, ConfigKey: "fold_close"},
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true, ConfigKey: "fold_open"},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true, ConfigKey: "fold_toggle"},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true, ConfigKey: "fold_open_all"},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true, ConfigKey: "fold_close_all"},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true, ConfigKey: "focus_selected"},
					{Name: "focus ecosystem/project", Keys: []string{"@"}, Description: "focus ecosystem/project", Enabled: true, ConfigKey: "focus_ecosystem"},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true, ConfigKey: "clear_focus"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run", Keys: []string{"r", "enter"}, Description: "run", Enabled: true, ConfigKey: "run"},
					{Name: "run in debug mode", Keys: []string{"d"}, Description: "run in debug mode", Enabled: true, ConfigKey: "debug_run"},
					{Name: "run in debug session", Keys: []string{"D"}, Description: "run in debug session", Enabled: true, ConfigKey: "debug_session"},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true, ConfigKey: "search"},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
	{
		Name:        "tend-sessions",
		Package:     "tend",
		Description: "Debug session manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true, ConfigKey: "up"},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true, ConfigKey: "down"},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true, ConfigKey: "page_up"},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true, ConfigKey: "page_down"},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "attach to session", Keys: []string{"enter"}, Description: "attach to session", Enabled: true, ConfigKey: "attach"},
					{Name: "kill session", Keys: []string{"x", "X"}, Description: "kill session", Enabled: true, ConfigKey: "kill"},
					{Name: "refresh list", Keys: []string{"r"}, Description: "refresh list", Enabled: true, ConfigKey: "refresh"},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true, ConfigKey: "help"},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true, ConfigKey: "quit"},
				},
			},
		},
	},
}

// TUIRegistryEntry describes a TUI's keybindings.
type TUIRegistryEntry struct {
	Name        string
	Package     string
	Description string
	Sections    []SectionEntry
}

// SectionEntry describes a keybinding section within a TUI.
type SectionEntry struct {
	Name     string
	Bindings []BindingEntry
}

// BindingEntry describes a single keybinding.
type BindingEntry struct {
	Name        string
	Keys        []string
	Description string
	Enabled     bool
	ConfigKey   string
}

// GetTUIByName returns the TUI registry entry for the given name.
func GetTUIByName(name string) *TUIRegistryEntry {
	for i := range TUIRegistry {
		if TUIRegistry[i].Name == name {
			return &TUIRegistry[i]
		}
	}
	return nil
}

// GetTUIsByPackage returns all TUI registry entries for the given package.
func GetTUIsByPackage(pkg string) []TUIRegistryEntry {
	var result []TUIRegistryEntry
	for _, tui := range TUIRegistry {
		if tui.Package == pkg {
			result = append(result, tui)
		}
	}
	return result
}

// AllBindings returns a flat list of all bindings across all TUIs.
func AllBindings() []FlatBinding {
	var result []FlatBinding
	for _, tui := range TUIRegistry {
		for _, section := range tui.Sections {
			for _, binding := range section.Bindings {
				result = append(result, FlatBinding{
					TUI:         tui.Name,
					Package:     tui.Package,
					Section:     section.Name,
					Name:        binding.Name,
					Keys:        binding.Keys,
					Description: binding.Description,
					Enabled:     binding.Enabled,
					ConfigKey:   binding.ConfigKey,
				})
			}
		}
	}
	return result
}

// FlatBinding is a denormalized binding with TUI context.
type FlatBinding struct {
	TUI         string
	Package     string
	Section     string
	Name        string
	Keys        []string
	Description string
	Enabled     bool
	ConfigKey   string
}
