// Code generated by keys-registry-generator. DO NOT EDIT.
// Run 'make keys-registry' to regenerate.

package keys

// TUIRegistry contains keybinding information for all TUIs in the ecosystem.
// This is populated at build time by the keys-registry-generator tool.
var TUIRegistry = []TUIRegistryEntry{
	{
		Name:        "cx-rules",
		Package:     "cx",
		Description: "Context rules picker and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
				},
			},
			{
				Name: "Rules",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"enter"}, Description: "select", Enabled: true},
					{Name: "load to .grove/rules", Keys: []string{"l"}, Description: "load to .grove/rules", Enabled: true},
					{Name: "save", Keys: []string{"s"}, Description: "save", Enabled: true},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true},
					{Name: "delete", Keys: []string{"d"}, Description: "delete", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "cx-view",
		Package:     "cx",
		Description: "Context viewer with tree, stats, and list pages",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "go to top", Keys: []string{"g"}, Description: "go to top", Enabled: true},
					{Name: "go to bottom", Keys: []string{"G"}, Description: "go to bottom", Enabled: true},
					{Name: "half page up", Keys: []string{"ctrl+u"}, Description: "half page up", Enabled: true},
					{Name: "half page down", Keys: []string{"ctrl+d"}, Description: "half page down", Enabled: true},
				},
			},
			{
				Name: "Pages",
				Bindings: []BindingEntry{
					{Name: "next page", Keys: []string{"tab"}, Description: "next page", Enabled: true},
					{Name: "prev page", Keys: []string{"shift+tab"}, Description: "prev page", Enabled: true},
				},
			},
			{
				Name: "Rules",
				Bindings: []BindingEntry{
					{Name: "edit rules", Keys: []string{"e"}, Description: "edit rules", Enabled: true},
					{Name: "select rule set", Keys: []string{"s"}, Description: "select rule set", Enabled: true},
					{Name: "exclude file", Keys: []string{"x"}, Description: "exclude file", Enabled: true},
					{Name: "exclude dir", Keys: []string{"X"}, Description: "exclude dir", Enabled: true},
					{Name: "refresh", Keys: []string{"r"}, Description: "refresh", Enabled: true},
				},
			},
			{
				Name: "Display",
				Bindings: []BindingEntry{
					{Name: "toggle sort", Keys: []string{"t"}, Description: "toggle sort", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-plan-add",
		Package:     "flow",
		Description: "Add new job to a plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "next field", Keys: []string{"tab"}, Description: "next field", Enabled: true},
					{Name: "prev field", Keys: []string{"shift+tab"}, Description: "prev field", Enabled: true},
					{Name: "go to top", Keys: []string{"gg", "home"}, Description: "go to top", Enabled: true},
					{Name: "go to bottom", Keys: []string{"G", "end"}, Description: "go to bottom", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "toggle", Keys: []string{" "}, Description: "toggle", Enabled: true},
					{Name: "submit", Keys: []string{"ctrl+s"}, Description: "submit", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-plan-finish",
		Package:     "flow",
		Description: "Finish and clean up a plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "toggle selection", Keys: []string{" "}, Description: "toggle selection", Enabled: true},
					{Name: "select all", Keys: []string{"a"}, Description: "select all", Enabled: true},
					{Name: "select none", Keys: []string{"n"}, Description: "select none", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm and proceed", Keys: []string{"enter"}, Description: "confirm and proceed", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-plan-init",
		Package:     "flow",
		Description: "Create a new plan",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "next field", Keys: []string{"tab", "j"}, Description: "next field", Enabled: true},
					{Name: "prev field", Keys: []string{"shift+tab", "k"}, Description: "prev field", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "toggle checkbox", Keys: []string{" "}, Description: "toggle checkbox", Enabled: true},
					{Name: "submit form", Keys: []string{"enter"}, Description: "submit form", Enabled: true},
					{Name: "toggle advanced", Keys: []string{"a"}, Description: "toggle advanced", Enabled: true},
					{Name: "insert mode", Keys: []string{"i"}, Description: "insert mode", Enabled: true},
					{Name: "normal mode", Keys: []string{"esc"}, Description: "normal mode", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "show help", Keys: []string{"?"}, Description: "show help", Enabled: true},
					{Name: "back to plan list", Keys: []string{"q"}, Description: "back to plan list", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-plan-list",
		Package:     "flow",
		Description: "Plan browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "move up", Keys: []string{"k", "up"}, Description: "move up", Enabled: true},
					{Name: "move down", Keys: []string{"j", "down"}, Description: "move down", Enabled: true},
					{Name: "view plan details", Keys: []string{"enter"}, Description: "view plan details", Enabled: true},
					{Name: "open plan workspace", Keys: []string{"o"}, Description: "open plan workspace", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "create new plan", Keys: []string{"n"}, Description: "create new plan", Enabled: true},
					{Name: "set active plan", Keys: []string{"s"}, Description: "set active plan", Enabled: true},
					{Name: "edit notes", Keys: []string{"e"}, Description: "edit notes", Enabled: true},
					{Name: "review changes", Keys: []string{"r"}, Description: "review changes", Enabled: true},
					{Name: "finish plan", Keys: []string{"ctrl+x"}, Description: "finish plan", Enabled: true},
					{Name: "hold/unhold plan", Keys: []string{"h"}, Description: "hold/unhold plan", Enabled: true},
					{Name: "update from main", Keys: []string{"U"}, Description: "update from main", Enabled: true},
					{Name: "merge to main", Keys: []string{"M"}, Description: "merge to main", Enabled: true},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle git log", Keys: []string{"g"}, Description: "toggle git log", Enabled: true},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-status",
		Package:     "flow",
		Description: "Flow plan status browser and job manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "toggle", Keys: []string{"v"}, Description: "toggle", Enabled: true},
					{Name: "all", Keys: []string{"a"}, Description: "all", Enabled: true},
					{Name: "none", Keys: []string{"A"}, Description: "none", Enabled: true},
				},
			},
			{
				Name: "Views",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true},
					{Name: "toggle columns", Keys: []string{"T"}, Description: "toggle columns", Enabled: true},
					{Name: "view logs", Keys: []string{"l"}, Description: "view logs", Enabled: true},
					{Name: "view frontmatter", Keys: []string{"f"}, Description: "view frontmatter", Enabled: true},
					{Name: "view briefing", Keys: []string{"b"}, Description: "view briefing", Enabled: true},
					{Name: "preview markdown", Keys: []string{"m", "p"}, Description: "preview markdown", Enabled: true},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true},
					{Name: "toggle detail pane", Keys: []string{"v"}, Description: "toggle detail pane", Enabled: true},
					{Name: "close detail pane", Keys: []string{"esc"}, Description: "close detail pane", Enabled: true},
					{Name: "switch focus", Keys: []string{"tab", "shift+tab"}, Description: "switch focus", Enabled: true},
					{Name: "toggle layout", Keys: []string{"V"}, Description: "toggle layout", Enabled: true},
					{Name: "fullscreen logs", Keys: []string{"z"}, Description: "fullscreen logs", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run job", Keys: []string{"r"}, Description: "run job", Enabled: true},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true},
					{Name: "mark completed", Keys: []string{"c"}, Description: "mark completed", Enabled: true},
					{Name: "set status", Keys: []string{"S"}, Description: "set status", Enabled: true},
					{Name: "set type", Keys: []string{"Y"}, Description: "set type", Enabled: true},
					{Name: "set template", Keys: []string{"E"}, Description: "set template", Enabled: true},
					{Name: "add job", Keys: []string{"A"}, Description: "add job", Enabled: true},
					{Name: "add from recipe", Keys: []string{"P"}, Description: "add from recipe", Enabled: true},
					{Name: "add XML plan job", Keys: []string{"x"}, Description: "add XML plan job", Enabled: true},
					{Name: "implement selected", Keys: []string{"i"}, Description: "implement selected", Enabled: true},
					{Name: "rename job", Keys: []string{"ctrl+r"}, Description: "rename job", Enabled: true},
					{Name: "resume job", Keys: []string{"R"}, Description: "resume job", Enabled: true},
					{Name: "edit dependencies", Keys: []string{"D"}, Description: "edit dependencies", Enabled: true},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "gemini-cache",
		Package:     "grove-gemini",
		Description: "Response cache browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "left", Keys: []string{"h", "left"}, Description: "left", Enabled: true},
					{Name: "right", Keys: []string{"l", "right"}, Description: "right", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "confirm", Keys: []string{"enter", "y"}, Description: "confirm", Enabled: true},
					{Name: "cancel", Keys: []string{"n", "ctrl+g"}, Description: "cancel", Enabled: true},
					{Name: "back", Keys: []string{"esc"}, Description: "back", Enabled: true},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true},
					{Name: "delete", Keys: []string{"dd"}, Description: "delete", Enabled: true},
					{Name: "yank", Keys: []string{"yy"}, Description: "yank", Enabled: true},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"space", "x"}, Description: "select", Enabled: true},
					{Name: "all", Keys: []string{"a"}, Description: "all", Enabled: true},
					{Name: "none", Keys: []string{"A"}, Description: "none", Enabled: true},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
			{
				Name: "Cache Actions",
				Bindings: []BindingEntry{
					{Name: "inspect", Keys: []string{"i", "enter"}, Description: "inspect", Enabled: true},
					{Name: "analytics", Keys: []string{"a"}, Description: "analytics", Enabled: true},
					{Name: "delete from API", Keys: []string{"d"}, Description: "delete from API", Enabled: true},
					{Name: "wipe local", Keys: []string{"w"}, Description: "wipe local", Enabled: true},
					{Name: "refresh", Keys: []string{"r"}, Description: "refresh", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "gemini-dashboard",
		Package:     "grove-gemini",
		Description: "BigQuery billing dashboard viewer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Time Frame",
				Bindings: []BindingEntry{
					{Name: "daily view", Keys: []string{"d"}, Description: "daily view", Enabled: true},
					{Name: "weekly view", Keys: []string{"w"}, Description: "weekly view", Enabled: true},
					{Name: "monthly view", Keys: []string{"m"}, Description: "monthly view", Enabled: true},
					{Name: "90-day view", Keys: []string{"3"}, Description: "90-day view", Enabled: true},
					{Name: "yearly view", Keys: []string{"y"}, Description: "yearly view", Enabled: true},
				},
			},
			{
				Name: "Period Navigation",
				Bindings: []BindingEntry{
					{Name: "previous period", Keys: []string{"left", "h"}, Description: "previous period", Enabled: true},
					{Name: "next period", Keys: []string{"right", "l"}, Description: "next period", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "gemini-query",
		Package:     "grove-gemini",
		Description: "Query usage analytics and logs viewer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Time Frame",
				Bindings: []BindingEntry{
					{Name: "daily view", Keys: []string{"d"}, Description: "daily view", Enabled: true},
					{Name: "weekly view", Keys: []string{"w"}, Description: "weekly view", Enabled: true},
					{Name: "monthly view", Keys: []string{"m"}, Description: "monthly view", Enabled: true},
				},
			},
			{
				Name: "Period Navigation",
				Bindings: []BindingEntry{
					{Name: "previous period", Keys: []string{"left", "h"}, Description: "previous period", Enabled: true},
					{Name: "next period", Keys: []string{"right", "l"}, Description: "next period", Enabled: true},
				},
			},
			{
				Name: "Display",
				Bindings: []BindingEntry{
					{Name: "toggle metric", Keys: []string{"t"}, Description: "toggle metric", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "grove-keys",
		Package:     "grove",
		Description: "Keybinding browser and analyzer",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "next tab", Keys: []string{"]"}, Description: "next tab", Enabled: true},
					{Name: "prev tab", Keys: []string{"["}, Description: "prev tab", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "toggle view", Keys: []string{"v"}, Description: "toggle view", Enabled: true},
					{Name: "edit config", Keys: []string{"e"}, Description: "edit config", Enabled: true},
				},
			},
			{
				Name: "Matrix View",
				Bindings: []BindingEntry{
					{Name: "scroll TUIs left", Keys: []string{"h"}, Description: "scroll TUIs left", Enabled: true},
					{Name: "scroll TUIs right", Keys: []string{"l"}, Description: "scroll TUIs right", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "hooks-browser",
		Package:     "hooks",
		Description: "Hook session browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "scroll up", Keys: []string{"ctrl+u", "pageup"}, Description: "scroll up", Enabled: true},
					{Name: "scroll down", Keys: []string{"ctrl+d", "pagedown"}, Description: "scroll down", Enabled: true},
					{Name: "go to top", Keys: []string{"g"}, Description: "go to top", Enabled: true},
					{Name: "go to bottom", Keys: []string{"G"}, Description: "go to bottom", Enabled: true},
					{Name: "jump", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"space", "x"}, Description: "select", Enabled: true},
					{Name: "select all", Keys: []string{"ctrl+a"}, Description: "select all", Enabled: true},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle view", Keys: []string{"t"}, Description: "toggle view", Enabled: true},
					{Name: "toggle filter view", Keys: []string{"f"}, Description: "toggle filter view", Enabled: true},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "action", Keys: []string{"e"}, Description: "action", Enabled: true},
					{Name: "action", Keys: []string{"o"}, Description: "action", Enabled: true},
					{Name: "copy id", Keys: []string{"ctrl+y"}, Description: "copy id", Enabled: true},
					{Name: "open dir", Keys: []string{"ctrl+o"}, Description: "open dir", Enabled: true},
					{Name: "export json", Keys: []string{"ctrl+j"}, Description: "export json", Enabled: true},
					{Name: "archive selected", Keys: []string{"ctrl+x"}, Description: "archive selected", Enabled: true},
				},
			},
			{
				Name: "Session",
				Bindings: []BindingEntry{
					{Name: "mark complete", Keys: []string{"c"}, Description: "mark complete", Enabled: true},
					{Name: "kill session", Keys: []string{"ctrl+k"}, Description: "kill session", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nav-history",
		Package:     "nav",
		Description: "Session history browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"up", "k"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"down", "j"}, Description: "down", Enabled: true},
					{Name: "jump to row", Keys: []string{"1-9"}, Description: "jump to row", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "filter", Keys: []string{"/"}, Description: "filter", Enabled: true},
					{Name: "switch to session", Keys: []string{"o", "enter"}, Description: "switch to session", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nav-manage",
		Package:     "nav",
		Description: "Session hotkey manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"up", "k"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"down", "j"}, Description: "down", Enabled: true},
					{Name: "jump to row", Keys: []string{"1-9"}, Description: "jump to row", Enabled: true},
					{Name: "switch to session", Keys: []string{"enter"}, Description: "switch to session", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "map CWD", Keys: []string{"e"}, Description: "map CWD", Enabled: true},
					{Name: "set key mode", Keys: []string{"h"}, Description: "set key mode", Enabled: true},
					{Name: "quick toggle", Keys: []string{" "}, Description: "quick toggle", Enabled: true},
					{Name: "clear mapping", Keys: []string{"d", "delete"}, Description: "clear mapping", Enabled: true},
					{Name: "save & exit", Keys: []string{"s", "ctrl+s"}, Description: "save & exit", Enabled: true},
				},
			},
			{
				Name: "Reorder",
				Bindings: []BindingEntry{
					{Name: "enter move mode", Keys: []string{"m"}, Description: "enter move mode", Enabled: true},
					{Name: "toggle lock", Keys: []string{"l"}, Description: "toggle lock", Enabled: true},
					{Name: "move row (in move mode)", Keys: []string{"j/k"}, Description: "move row (in move mode)", Enabled: true},
					{Name: "confirm move", Keys: []string{"enter"}, Description: "confirm move", Enabled: true},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle paths", Keys: []string{"p"}, Description: "toggle paths", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nav-sessionize",
		Package:     "nav",
		Description: "Tmux session switcher and workspace browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "select session", Keys: []string{"enter"}, Description: "select session", Enabled: true},
				},
			},
			{
				Name: "Session",
				Bindings: []BindingEntry{
					{Name: "refresh project list", Keys: []string{"ctrl+r"}, Description: "refresh project list", Enabled: true},
					{Name: "edit key mapping", Keys: []string{"ctrl+e"}, Description: "edit key mapping", Enabled: true},
					{Name: "clear key mapping", Keys: []string{"ctrl+x"}, Description: "clear key mapping", Enabled: true},
					{Name: "copy path to clipboard", Keys: []string{"ctrl+y"}, Description: "copy path to clipboard", Enabled: true},
					{Name: "close session", Keys: []string{"X"}, Description: "close session", Enabled: true},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus on project", Keys: []string{"@"}, Description: "focus on project", Enabled: true},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true},
					{Name: "toggle worktrees", Keys: []string{"tab"}, Description: "toggle worktrees", Enabled: true},
					{Name: "filter dirty", Keys: []string{"D"}, Description: "filter dirty", Enabled: true},
					{Name: "toggle context", Keys: []string{"C"}, Description: "toggle context", Enabled: true},
				},
			},
			{
				Name: "Columns",
				Bindings: []BindingEntry{
					{Name: "toggle cx column", Keys: []string{"c"}, Description: "toggle cx column", Enabled: true},
					{Name: "toggle git status", Keys: []string{"s"}, Description: "toggle git status", Enabled: true},
					{Name: "toggle branch names", Keys: []string{"b"}, Description: "toggle branch names", Enabled: true},
					{Name: "toggle note counts", Keys: []string{"n"}, Description: "toggle note counts", Enabled: true},
					{Name: "toggle flow plans", Keys: []string{"f"}, Description: "toggle flow plans", Enabled: true},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true},
					{Name: "toggle full paths", Keys: []string{"p"}, Description: "toggle full paths", Enabled: true},
					{Name: "toggle release", Keys: []string{"r"}, Description: "toggle release", Enabled: true},
					{Name: "toggle tool/version", Keys: []string{"y"}, Description: "toggle tool/version", Enabled: true},
					{Name: "toggle remote", Keys: []string{"l"}, Description: "toggle remote", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nav-windows",
		Package:     "nav",
		Description: "Tmux window manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "jump to window", Keys: []string{"0-9"}, Description: "jump to window", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "switch", Keys: []string{"enter"}, Description: "switch", Enabled: true},
					{Name: "filter", Keys: []string{"/"}, Description: "filter", Enabled: true},
					{Name: "rename", Keys: []string{"r"}, Description: "rename", Enabled: true},
					{Name: "close", Keys: []string{"X"}, Description: "close", Enabled: true},
				},
			},
			{
				Name: "Reorder",
				Bindings: []BindingEntry{
					{Name: "move window", Keys: []string{"m"}, Description: "move window", Enabled: true},
					{Name: "move (in move mode)", Keys: []string{"j/k"}, Description: "move (in move mode)", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nb-browser",
		Package:     "nb",
		Description: "Notebook browser and note manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "left", Keys: []string{"h", "left"}, Description: "left", Enabled: true},
					{Name: "right", Keys: []string{"l", "right"}, Description: "right", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"space", "x"}, Description: "select", Enabled: true},
					{Name: "all", Keys: []string{"a"}, Description: "all", Enabled: true},
					{Name: "none", Keys: []string{"A"}, Description: "none", Enabled: true},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus ecosystem", Keys: []string{"@"}, Description: "focus ecosystem", Enabled: true},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true},
					{Name: "focus parent (disabled)", Keys: []string{""}, Description: "focus parent (disabled)", Enabled: true},
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true},
					{Name: "focus recent", Keys: []string{"f"}, Description: "focus recent", Enabled: true},
					{Name: "jump to workspace", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump to workspace", Enabled: true},
				},
			},
			{
				Name: "Filter",
				Bindings: []BindingEntry{
					{Name: "filter by tag", Keys: []string{"&"}, Description: "filter by tag", Enabled: true},
					{Name: "git changes", Keys: []string{"<", ">"}, Description: "git changes", Enabled: true},
					{Name: "toggle sort order", Keys: []string{"s"}, Description: "toggle sort order", Enabled: true},
				},
			},
			{
				Name: "Toggle",
				Bindings: []BindingEntry{
					{Name: "toggle archives", Keys: []string{"A"}, Description: "toggle archives", Enabled: true},
					{Name: "toggle artifacts", Keys: []string{"b"}, Description: "toggle artifacts", Enabled: true},
					{Name: "toggle global", Keys: []string{"~"}, Description: "toggle global", Enabled: true},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true},
					{Name: "toggle columns", Keys: []string{"V"}, Description: "toggle columns", Enabled: true},
				},
			},
			{
				Name: "Notes",
				Bindings: []BindingEntry{
					{Name: "create note at cursor", Keys: []string{"n"}, Description: "create note at cursor", Enabled: true},
					{Name: "inbox note (quick capture)", Keys: []string{"i"}, Description: "inbox note (quick capture)", Enabled: true},
					{Name: "global note", Keys: []string{"I"}, Description: "global note", Enabled: true},
					{Name: "promote note to plan", Keys: []string{"P"}, Description: "promote note to plan", Enabled: true},
					{Name: "rename note", Keys: []string{"r"}, Description: "rename note", Enabled: true},
				},
			},
			{
				Name: "Clipboard",
				Bindings: []BindingEntry{
					{Name: "cut selected", Keys: []string{"x"}, Description: "cut selected", Enabled: true},
					{Name: "copy selected", Keys: []string{"y", "c"}, Description: "copy selected", Enabled: true},
					{Name: "paste from clipboard", Keys: []string{"p"}, Description: "paste from clipboard", Enabled: true},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true},
				},
			},
			{
				Name: "Git",
				Bindings: []BindingEntry{
					{Name: "toggle git stage", Keys: []string{"-"}, Description: "toggle git stage", Enabled: true},
					{Name: "stage all", Keys: []string{"="}, Description: "stage all", Enabled: true},
					{Name: "unstage all", Keys: []string{"+"}, Description: "unstage all", Enabled: true},
					{Name: "git commit", Keys: []string{"C"}, Description: "git commit", Enabled: true},
				},
			},
			{
				Name: "Misc",
				Bindings: []BindingEntry{
					{Name: "toggle preview focus", Keys: []string{"tab"}, Description: "toggle preview focus", Enabled: true},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true},
					{Name: "sync with remotes", Keys: []string{"S"}, Description: "sync with remotes", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "tend-runner",
		Package:     "tend",
		Description: "Test runner and e2e test browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true},
					{Name: "focus ecosystem/project", Keys: []string{"@"}, Description: "focus ecosystem/project", Enabled: true},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run", Keys: []string{"r", "enter"}, Description: "run", Enabled: true},
					{Name: "run in debug mode", Keys: []string{"d"}, Description: "run in debug mode", Enabled: true},
					{Name: "run in debug session", Keys: []string{"D"}, Description: "run in debug session", Enabled: true},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "tend-sessions",
		Package:     "tend",
		Description: "Debug session manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "attach to session", Keys: []string{"enter"}, Description: "attach to session", Enabled: true},
					{Name: "kill session", Keys: []string{"x", "X"}, Description: "kill session", Enabled: true},
					{Name: "refresh list", Keys: []string{"r"}, Description: "refresh list", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
}

// TUIRegistryEntry describes a TUI's keybindings.
type TUIRegistryEntry struct {
	Name        string
	Package     string
	Description string
	Sections    []SectionEntry
}

// SectionEntry describes a keybinding section within a TUI.
type SectionEntry struct {
	Name     string
	Bindings []BindingEntry
}

// BindingEntry describes a single keybinding.
type BindingEntry struct {
	Name        string
	Keys        []string
	Description string
	Enabled     bool
}

// GetTUIByName returns the TUI registry entry for the given name.
func GetTUIByName(name string) *TUIRegistryEntry {
	for i := range TUIRegistry {
		if TUIRegistry[i].Name == name {
			return &TUIRegistry[i]
		}
	}
	return nil
}

// GetTUIsByPackage returns all TUI registry entries for the given package.
func GetTUIsByPackage(pkg string) []TUIRegistryEntry {
	var result []TUIRegistryEntry
	for _, tui := range TUIRegistry {
		if tui.Package == pkg {
			result = append(result, tui)
		}
	}
	return result
}

// AllBindings returns a flat list of all bindings across all TUIs.
func AllBindings() []FlatBinding {
	var result []FlatBinding
	for _, tui := range TUIRegistry {
		for _, section := range tui.Sections {
			for _, binding := range section.Bindings {
				result = append(result, FlatBinding{
					TUI:         tui.Name,
					Package:     tui.Package,
					Section:     section.Name,
					Name:        binding.Name,
					Keys:        binding.Keys,
					Description: binding.Description,
					Enabled:     binding.Enabled,
				})
			}
		}
	}
	return result
}

// FlatBinding is a denormalized binding with TUI context.
type FlatBinding struct {
	TUI         string
	Package     string
	Section     string
	Name        string
	Keys        []string
	Description string
	Enabled     bool
}
