// Code generated by keys-registry-generator. DO NOT EDIT.
// Run 'make keys-registry' to regenerate.

package keys

// TUIRegistry contains keybinding information for all TUIs in the ecosystem.
// This is populated at build time by the keys-registry-generator tool.
var TUIRegistry = []TUIRegistryEntry{
	{
		Name:        "cx-rules",
		Package:     "cx",
		Description: "Context rules picker and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
				},
			},
			{
				Name: "Rules",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"enter"}, Description: "select", Enabled: true},
					{Name: "load to .grove/rules", Keys: []string{"l"}, Description: "load to .grove/rules", Enabled: true},
					{Name: "save", Keys: []string{"s"}, Description: "save", Enabled: true},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true},
					{Name: "delete", Keys: []string{"d"}, Description: "delete", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "flow-status",
		Package:     "flow",
		Description: "Flow plan status browser and job manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "toggle", Keys: []string{"v"}, Description: "toggle", Enabled: true},
					{Name: "all", Keys: []string{"a"}, Description: "all", Enabled: true},
					{Name: "none", Keys: []string{"A"}, Description: "none", Enabled: true},
				},
			},
			{
				Name: "Views",
				Bindings: []BindingEntry{
					{Name: "switch view", Keys: []string{"tab"}, Description: "switch view", Enabled: true},
					{Name: "toggle columns", Keys: []string{"T"}, Description: "toggle columns", Enabled: true},
					{Name: "view logs", Keys: []string{"l"}, Description: "view logs", Enabled: true},
					{Name: "view frontmatter", Keys: []string{"f"}, Description: "view frontmatter", Enabled: true},
					{Name: "view briefing", Keys: []string{"b"}, Description: "view briefing", Enabled: true},
					{Name: "preview markdown", Keys: []string{"m", "p"}, Description: "preview markdown", Enabled: true},
					{Name: "preview", Keys: []string{"v"}, Description: "preview", Enabled: true},
					{Name: "toggle detail pane", Keys: []string{"v"}, Description: "toggle detail pane", Enabled: true},
					{Name: "close detail pane", Keys: []string{"esc"}, Description: "close detail pane", Enabled: true},
					{Name: "switch focus", Keys: []string{"tab", "shift+tab"}, Description: "switch focus", Enabled: true},
					{Name: "toggle layout", Keys: []string{"V"}, Description: "toggle layout", Enabled: true},
					{Name: "fullscreen logs", Keys: []string{"z"}, Description: "fullscreen logs", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run job", Keys: []string{"r"}, Description: "run job", Enabled: true},
					{Name: "edit", Keys: []string{"e"}, Description: "edit", Enabled: true},
					{Name: "mark completed", Keys: []string{"c"}, Description: "mark completed", Enabled: true},
					{Name: "set status", Keys: []string{"S"}, Description: "set status", Enabled: true},
					{Name: "set type", Keys: []string{"Y"}, Description: "set type", Enabled: true},
					{Name: "set template", Keys: []string{"E"}, Description: "set template", Enabled: true},
					{Name: "add job", Keys: []string{"A"}, Description: "add job", Enabled: true},
					{Name: "add from recipe", Keys: []string{"P"}, Description: "add from recipe", Enabled: true},
					{Name: "add XML plan job", Keys: []string{"x"}, Description: "add XML plan job", Enabled: true},
					{Name: "implement selected", Keys: []string{"i"}, Description: "implement selected", Enabled: true},
					{Name: "rename job", Keys: []string{"ctrl+r"}, Description: "rename job", Enabled: true},
					{Name: "resume job", Keys: []string{"R"}, Description: "resume job", Enabled: true},
					{Name: "edit dependencies", Keys: []string{"D"}, Description: "edit dependencies", Enabled: true},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "hooks-browser",
		Package:     "hooks",
		Description: "Hook session browser and manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "scroll up", Keys: []string{"ctrl+u", "pageup"}, Description: "scroll up", Enabled: true},
					{Name: "scroll down", Keys: []string{"ctrl+d", "pagedown"}, Description: "scroll down", Enabled: true},
					{Name: "go to top", Keys: []string{"g"}, Description: "go to top", Enabled: true},
					{Name: "go to bottom", Keys: []string{"G"}, Description: "go to bottom", Enabled: true},
					{Name: "jump", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"space", "x"}, Description: "select", Enabled: true},
					{Name: "select all", Keys: []string{"ctrl+a"}, Description: "select all", Enabled: true},
				},
			},
			{
				Name: "View",
				Bindings: []BindingEntry{
					{Name: "toggle view", Keys: []string{"t"}, Description: "toggle view", Enabled: true},
					{Name: "toggle filter view", Keys: []string{"f"}, Description: "toggle filter view", Enabled: true},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "action", Keys: []string{"e"}, Description: "action", Enabled: true},
					{Name: "action", Keys: []string{"o"}, Description: "action", Enabled: true},
					{Name: "copy id", Keys: []string{"ctrl+y"}, Description: "copy id", Enabled: true},
					{Name: "open dir", Keys: []string{"ctrl+o"}, Description: "open dir", Enabled: true},
					{Name: "export json", Keys: []string{"ctrl+j"}, Description: "export json", Enabled: true},
					{Name: "archive selected", Keys: []string{"ctrl+x"}, Description: "archive selected", Enabled: true},
				},
			},
			{
				Name: "Session",
				Bindings: []BindingEntry{
					{Name: "mark complete", Keys: []string{"c"}, Description: "mark complete", Enabled: true},
					{Name: "kill session", Keys: []string{"ctrl+k"}, Description: "kill session", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "nb-browser",
		Package:     "nb",
		Description: "Notebook browser and note manager",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "left", Keys: []string{"h", "left"}, Description: "left", Enabled: true},
					{Name: "right", Keys: []string{"l", "right"}, Description: "right", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Selection",
				Bindings: []BindingEntry{
					{Name: "select", Keys: []string{"space", "x"}, Description: "select", Enabled: true},
					{Name: "all", Keys: []string{"a"}, Description: "all", Enabled: true},
					{Name: "none", Keys: []string{"A"}, Description: "none", Enabled: true},
				},
			},
			{
				Name: "Search",
				Bindings: []BindingEntry{
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "next match", Keys: []string{"n"}, Description: "next match", Enabled: true},
					{Name: "prev match", Keys: []string{"N"}, Description: "prev match", Enabled: true},
					{Name: "clear search", Keys: []string{"ctrl+l"}, Description: "clear search", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus ecosystem", Keys: []string{"@"}, Description: "focus ecosystem", Enabled: true},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true},
					{Name: "focus parent (disabled)", Keys: []string{""}, Description: "focus parent (disabled)", Enabled: true},
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true},
					{Name: "focus recent", Keys: []string{"f"}, Description: "focus recent", Enabled: true},
					{Name: "jump to workspace", Keys: []string{"1", "2", "3", "4", "5", "6", "7", "8", "9"}, Description: "jump to workspace", Enabled: true},
				},
			},
			{
				Name: "Filter",
				Bindings: []BindingEntry{
					{Name: "filter by tag", Keys: []string{"&"}, Description: "filter by tag", Enabled: true},
					{Name: "git changes", Keys: []string{"<", ">"}, Description: "git changes", Enabled: true},
					{Name: "toggle sort order", Keys: []string{"s"}, Description: "toggle sort order", Enabled: true},
				},
			},
			{
				Name: "Toggle",
				Bindings: []BindingEntry{
					{Name: "toggle archives", Keys: []string{"A"}, Description: "toggle archives", Enabled: true},
					{Name: "toggle artifacts", Keys: []string{"b"}, Description: "toggle artifacts", Enabled: true},
					{Name: "toggle global", Keys: []string{"~"}, Description: "toggle global", Enabled: true},
					{Name: "toggle on-hold", Keys: []string{"H"}, Description: "toggle on-hold", Enabled: true},
					{Name: "toggle columns", Keys: []string{"V"}, Description: "toggle columns", Enabled: true},
				},
			},
			{
				Name: "Notes",
				Bindings: []BindingEntry{
					{Name: "create note at cursor", Keys: []string{"n"}, Description: "create note at cursor", Enabled: true},
					{Name: "inbox note (quick capture)", Keys: []string{"i"}, Description: "inbox note (quick capture)", Enabled: true},
					{Name: "global note", Keys: []string{"I"}, Description: "global note", Enabled: true},
					{Name: "promote note to plan", Keys: []string{"P"}, Description: "promote note to plan", Enabled: true},
					{Name: "rename note", Keys: []string{"r"}, Description: "rename note", Enabled: true},
				},
			},
			{
				Name: "Clipboard",
				Bindings: []BindingEntry{
					{Name: "cut selected", Keys: []string{"x"}, Description: "cut selected", Enabled: true},
					{Name: "copy selected", Keys: []string{"y", "c"}, Description: "copy selected", Enabled: true},
					{Name: "paste from clipboard", Keys: []string{"p"}, Description: "paste from clipboard", Enabled: true},
					{Name: "archive selected", Keys: []string{"X"}, Description: "archive selected", Enabled: true},
				},
			},
			{
				Name: "Git",
				Bindings: []BindingEntry{
					{Name: "toggle git stage", Keys: []string{"-"}, Description: "toggle git stage", Enabled: true},
					{Name: "stage all", Keys: []string{"="}, Description: "stage all", Enabled: true},
					{Name: "unstage all", Keys: []string{"+"}, Description: "unstage all", Enabled: true},
					{Name: "git commit", Keys: []string{"C"}, Description: "git commit", Enabled: true},
				},
			},
			{
				Name: "Misc",
				Bindings: []BindingEntry{
					{Name: "toggle preview focus", Keys: []string{"tab"}, Description: "toggle preview focus", Enabled: true},
					{Name: "refresh", Keys: []string{"ctrl+r"}, Description: "refresh", Enabled: true},
					{Name: "sync with remotes", Keys: []string{"S"}, Description: "sync with remotes", Enabled: true},
				},
			},
			{
				Name: "System",
				Bindings: []BindingEntry{
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
	{
		Name:        "tend-runner",
		Package:     "tend",
		Description: "Test runner and e2e test browser",
		Sections: []SectionEntry{
			{
				Name: "Navigation",
				Bindings: []BindingEntry{
					{Name: "up", Keys: []string{"k", "up"}, Description: "up", Enabled: true},
					{Name: "down", Keys: []string{"j", "down"}, Description: "down", Enabled: true},
					{Name: "page up", Keys: []string{"ctrl+u", "pgup"}, Description: "page up", Enabled: true},
					{Name: "page down", Keys: []string{"ctrl+d", "pgdown"}, Description: "page down", Enabled: true},
					{Name: "top", Keys: []string{"gg"}, Description: "top", Enabled: true},
					{Name: "bottom", Keys: []string{"G"}, Description: "bottom", Enabled: true},
				},
			},
			{
				Name: "Fold",
				Bindings: []BindingEntry{
					{Name: "close fold", Keys: []string{"zc"}, Description: "close fold", Enabled: true},
					{Name: "open fold", Keys: []string{"zo"}, Description: "open fold", Enabled: true},
					{Name: "toggle fold", Keys: []string{"za"}, Description: "toggle fold", Enabled: true},
					{Name: "open all", Keys: []string{"zR"}, Description: "open all", Enabled: true},
					{Name: "close all", Keys: []string{"zM"}, Description: "close all", Enabled: true},
				},
			},
			{
				Name: "Focus",
				Bindings: []BindingEntry{
					{Name: "focus selected", Keys: []string{"."}, Description: "focus selected", Enabled: true},
					{Name: "focus ecosystem/project", Keys: []string{"@"}, Description: "focus ecosystem/project", Enabled: true},
					{Name: "clear focus", Keys: []string{"ctrl+g"}, Description: "clear focus", Enabled: true},
				},
			},
			{
				Name: "Actions",
				Bindings: []BindingEntry{
					{Name: "run", Keys: []string{"r", "enter"}, Description: "run", Enabled: true},
					{Name: "run in debug mode", Keys: []string{"d"}, Description: "run in debug mode", Enabled: true},
					{Name: "run in debug session", Keys: []string{"D"}, Description: "run in debug session", Enabled: true},
					{Name: "search", Keys: []string{"/"}, Description: "search", Enabled: true},
					{Name: "help", Keys: []string{"?"}, Description: "help", Enabled: true},
					{Name: "quit", Keys: []string{"q", "ctrl+c"}, Description: "quit", Enabled: true},
				},
			},
		},
	},
}

// TUIRegistryEntry describes a TUI's keybindings.
type TUIRegistryEntry struct {
	Name        string
	Package     string
	Description string
	Sections    []SectionEntry
}

// SectionEntry describes a keybinding section within a TUI.
type SectionEntry struct {
	Name     string
	Bindings []BindingEntry
}

// BindingEntry describes a single keybinding.
type BindingEntry struct {
	Name        string
	Keys        []string
	Description string
	Enabled     bool
}

// GetTUIByName returns the TUI registry entry for the given name.
func GetTUIByName(name string) *TUIRegistryEntry {
	for i := range TUIRegistry {
		if TUIRegistry[i].Name == name {
			return &TUIRegistry[i]
		}
	}
	return nil
}

// GetTUIsByPackage returns all TUI registry entries for the given package.
func GetTUIsByPackage(pkg string) []TUIRegistryEntry {
	var result []TUIRegistryEntry
	for _, tui := range TUIRegistry {
		if tui.Package == pkg {
			result = append(result, tui)
		}
	}
	return result
}

// AllBindings returns a flat list of all bindings across all TUIs.
func AllBindings() []FlatBinding {
	var result []FlatBinding
	for _, tui := range TUIRegistry {
		for _, section := range tui.Sections {
			for _, binding := range section.Bindings {
				result = append(result, FlatBinding{
					TUI:         tui.Name,
					Package:     tui.Package,
					Section:     section.Name,
					Name:        binding.Name,
					Keys:        binding.Keys,
					Description: binding.Description,
					Enabled:     binding.Enabled,
				})
			}
		}
	}
	return result
}

// FlatBinding is a denormalized binding with TUI context.
type FlatBinding struct {
	TUI         string
	Package     string
	Section     string
	Name        string
	Keys        []string
	Description string
	Enabled     bool
}
