package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/grovetools/core/cli"
	"github.com/grovetools/core/config"
	"github.com/grovetools/core/pkg/keybind"
	"github.com/grovetools/core/pkg/paths"
	"github.com/grovetools/core/tui/theme"
	"github.com/spf13/cobra"

	"github.com/grovetools/grove/pkg/keys"
)

// newKeysGenerateNvimCmd creates the 'grove keys generate nvim' command.
func newKeysGenerateNvimCmd() *cobra.Command {
	var dryRun bool
	var outputPath string

	cmd := cli.NewStandardCommand("nvim", "Generate Neovim keybinding configuration")

	cmd.Long = `Generate a Lua configuration file from [keys.nvim] config.

The generated file contains vim.keymap.set() calls that can be sourced
from your Neovim init.lua configuration.

Output: ~/.cache/grove/nvim/grove-keymaps.lua`

	cmd.Example = `  # Generate nvim config
  grove keys generate nvim

  # Preview without writing
  grove keys generate nvim --dry-run

  # Custom output path
  grove keys generate nvim --output /path/to/keymaps.lua`

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		return runKeysGenerateNvim(outputPath, dryRun)
	}

	cmd.Flags().BoolVarP(&dryRun, "dry-run", "n", false, "Print output without writing to file")
	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "Output file path (default: ~/.cache/grove/nvim/grove-keymaps.lua)")

	return cmd
}

func runKeysGenerateNvim(outputPath string, dryRun bool) error {
	cfg, err := config.LoadDefault()
	if err != nil {
		cfg = &config.Config{}
	}

	t := theme.DefaultTheme

	// Load keys extension
	var keysExt keys.KeysExtension
	if cfg != nil {
		_ = cfg.UnmarshalExtension("keys", &keysExt)
	}

	// Check if nvim bindings are configured
	if !keysExt.Nvim.Enabled {
		fmt.Println(t.Warning.Render(theme.IconWarning + " Neovim keybindings not enabled in grove.toml"))
		fmt.Println(t.Muted.Render("Add nvim bindings to your grove.toml:"))
		fmt.Println()
		fmt.Println(t.Code.Render(`[keys.nvim]
enabled = true

[keys.nvim.bindings."<leader>gp"]
command = ":GroveStatus<CR>"
mode = "n"
desc = "Grove status"

[keys.nvim.bindings."<leader>gn"]
command = ":GroveNotebook<CR>"
mode = "n"
desc = "Grove notebook"`))
		return nil
	}

	if len(keysExt.Nvim.Bindings) == 0 {
		fmt.Println(t.Warning.Render(theme.IconWarning + " No [keys.nvim.bindings] defined in grove.toml"))
		return nil
	}

	// Generate the config
	return generateNvimConfig(keysExt.Nvim, outputPath, dryRun, t)
}

func generateNvimConfig(nvimCfg keys.NvimKeysConfig, outputPath string, dryRun bool, t *theme.Theme) error {
	// Build the Lua configuration content
	var lines []string

	// Header
	lines = append(lines, "-- Grove Neovim keybindings")
	lines = append(lines, "-- Generated by: grove keys generate nvim")
	lines = append(lines, fmt.Sprintf("-- Last updated: %s", time.Now().Format("2006-01-02 15:04:05")))
	lines = append(lines, "--")
	lines = append(lines, "-- Source this file in your init.lua:")
	lines = append(lines, "--   dofile(vim.fn.expand('~/.cache/grove/nvim/grove-keymaps.lua'))")
	lines = append(lines, "-- Or require it if in your runtimepath:")
	lines = append(lines, "--   require('grove-keymaps')")
	lines = append(lines, "")

	// Sort keys for consistent output
	var sortedKeys []string
	for k := range nvimCfg.Bindings {
		sortedKeys = append(sortedKeys, k)
	}
	sort.Strings(sortedKeys)

	// Generate vim.keymap.set() calls
	for _, key := range sortedKeys {
		binding := nvimCfg.Bindings[key]

		// Default values
		mode := binding.Mode
		if mode == "" {
			mode = "n" // Default to normal mode
		}

		cmd := binding.Command
		desc := binding.Desc
		silent := binding.Silent
		noremap := binding.NoRemap

		// If NoRemap is not explicitly set, default to true
		// (We can't distinguish between false and unset in Go, so we'll assume
		// noremap=true by default which is safer for keybindings)
		_ = noremap // All vim.keymap.set calls are noremap by default

		// Denormalize key to nvim format
		nvimKey := keybind.Denormalize(keybind.Normalize(key, "nvim"), "nvim")

		// If the key already looks like nvim format, use it directly
		if strings.HasPrefix(key, "<") && strings.HasSuffix(key, ">") {
			nvimKey = key
		}

		// Build options table
		var opts []string
		if desc != "" {
			opts = append(opts, fmt.Sprintf(`desc = %q`, desc))
		}
		if silent {
			opts = append(opts, "silent = true")
		}

		// Generate the vim.keymap.set call
		var line string
		if len(opts) > 0 {
			line = fmt.Sprintf(`vim.keymap.set(%q, %q, %q, { %s })`, mode, nvimKey, cmd, strings.Join(opts, ", "))
		} else {
			line = fmt.Sprintf(`vim.keymap.set(%q, %q, %q)`, mode, nvimKey, cmd)
		}
		lines = append(lines, line)
	}

	lines = append(lines, "")
	content := strings.Join(lines, "\n")

	// Determine output path
	if outputPath == "" {
		outputPath = filepath.Join(paths.CacheDir(), "nvim", "grove-keymaps.lua")
	}

	// Dry run: just print
	if dryRun {
		fmt.Println(t.Header.Render(theme.IconShell + " Generated Neovim configuration:"))
		fmt.Println()
		fmt.Println(content)
		return nil
	}

	// Create directory if needed
	outDir := filepath.Dir(outputPath)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", outDir, err)
	}

	// Write the file
	if err := os.WriteFile(outputPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write %s: %w", outputPath, err)
	}

	fmt.Printf("%s Generated: %s (%d bindings)\n", t.Success.Render(theme.IconSuccess), outputPath, len(nvimCfg.Bindings))
	fmt.Println()
	fmt.Println(t.Muted.Render("To use, add to your init.lua:"))
	fmt.Printf("  %s\n", t.Code.Render(fmt.Sprintf("dofile(vim.fn.expand('%s'))", outputPath)))

	return nil
}

// printNvimSourceInstructions prints instructions for sourcing generated nvim config.
func printNvimSourceInstructions(t *theme.Theme) {
	fmt.Println()
	fmt.Println(t.Muted.Render("  Neovim (~/.config/nvim/init.lua):"))
	fmt.Printf("    %s\n", t.Code.Render(fmt.Sprintf("dofile(vim.fn.expand('%s/nvim/grove-keymaps.lua'))", paths.CacheDir())))
}
