package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/grovetools/core/cli"
	"github.com/grovetools/core/config"
	"github.com/grovetools/core/pkg/keybind"
	"github.com/grovetools/core/pkg/paths"
	"github.com/grovetools/core/tui/theme"
	"github.com/grovetools/grove/pkg/keys"
	"github.com/spf13/cobra"
)

// newKeysGenerateShellCmd creates the 'grove keys generate shell' command.
func newKeysGenerateShellCmd() *cobra.Command {
	var targetShell string
	var dryRun bool

	cmd := cli.NewStandardCommand("shell", "Generate shell keybinding configurations")

	cmd.Long = `Generate shell configuration files from [keys.shell] config.

Supported shells:
  fish    Generate ~/.cache/grove/fish/grove-bindings.fish
  bash    Generate ~/.cache/grove/bash/grove-bindings.bash
  zsh     Generate ~/.cache/grove/zsh/grove-bindings.zsh
  all     Generate configs for all supported shells (default)

The generated files contain shell-specific keybinding commands.
Source these files from your shell's configuration file.`

	cmd.Example = `  # Generate all shell configs
  grove keys generate shell

  # Generate only fish config
  grove keys generate shell --shell fish

  # Preview without writing
  grove keys generate shell --dry-run`

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		return runKeysGenerateShell(targetShell, dryRun)
	}

	cmd.Flags().StringVarP(&targetShell, "shell", "s", "all", "Target shell (fish, bash, zsh, or all)")
	cmd.Flags().BoolVarP(&dryRun, "dry-run", "n", false, "Print output without writing to file")

	return cmd
}

// shellConfig holds the configuration for a specific shell.
type shellConfig struct {
	name       string
	ext        string
	formatBind func(key, command string) string
	header     func() []string
	footer     func() []string
}

var supportedShells = map[string]shellConfig{
	"fish": {
		name: "fish",
		ext:  "fish",
		formatBind: func(key, command string) string {
			fishKey := keybind.Denormalize(key, "fish")
			return fmt.Sprintf("bind %s '%s'", fishKey, command)
		},
		header: func() []string {
			return []string{
				"# Grove shell keybindings for fish",
				"# Generated by: grove keys generate shell",
				fmt.Sprintf("# Last updated: %s", time.Now().Format("2006-01-02 15:04:05")),
				"#",
				"# Source this file in your ~/.config/fish/config.fish:",
				"#   source ~/.cache/grove/fish/grove-bindings.fish",
				"",
			}
		},
		footer: func() []string {
			return []string{""}
		},
	},
	"bash": {
		name: "bash",
		ext:  "bash",
		formatBind: func(key, command string) string {
			bashKey := keybind.Denormalize(key, "bash")
			return fmt.Sprintf("bind '\"%s\":\"%s\"'", bashKey, command)
		},
		header: func() []string {
			return []string{
				"# Grove shell keybindings for bash",
				"# Generated by: grove keys generate shell",
				fmt.Sprintf("# Last updated: %s", time.Now().Format("2006-01-02 15:04:05")),
				"#",
				"# Source this file in your ~/.bashrc:",
				"#   source ~/.cache/grove/bash/grove-bindings.bash",
				"",
			}
		},
		footer: func() []string {
			return []string{""}
		},
	},
	"zsh": {
		name: "zsh",
		ext:  "zsh",
		formatBind: func(key, command string) string {
			zshKey := keybind.Denormalize(key, "zsh")
			// Zsh needs a widget for command execution
			widgetName := strings.ReplaceAll(command, " ", "-")
			widgetName = strings.ReplaceAll(widgetName, "/", "-")
			return fmt.Sprintf(`# %s
%s() { BUFFER="%s"; zle accept-line }
zle -N %s
bindkey "%s" %s`, command, widgetName, command, widgetName, zshKey, widgetName)
		},
		header: func() []string {
			return []string{
				"# Grove shell keybindings for zsh",
				"# Generated by: grove keys generate shell",
				fmt.Sprintf("# Last updated: %s", time.Now().Format("2006-01-02 15:04:05")),
				"#",
				"# Source this file in your ~/.zshrc:",
				"#   source ~/.cache/grove/zsh/grove-bindings.zsh",
				"",
			}
		},
		footer: func() []string {
			return []string{""}
		},
	},
}

func runKeysGenerateShell(targetShell string, dryRun bool) error {
	cfg, err := config.LoadDefault()
	if err != nil {
		cfg = &config.Config{}
	}

	t := theme.DefaultTheme

	// Load keys extension
	var keysExt keys.KeysExtension
	if cfg != nil {
		_ = cfg.UnmarshalExtension("keys", &keysExt)
	}

	// Check if shell bindings are configured
	if !keysExt.Shell.Enabled {
		fmt.Println(t.Warning.Render(theme.IconWarning + " Shell keybindings not enabled in grove.toml"))
		fmt.Println(t.Muted.Render("Add shell bindings to your grove.toml:"))
		fmt.Println()
		fmt.Println(t.Code.Render(`[keys.shell]
enabled = true

[keys.shell.bindings]
"M-g" = "grove"     # Open grove TUI
"M-n" = "nb"        # Open notebook`))
		return nil
	}

	if len(keysExt.Shell.Bindings) == 0 {
		fmt.Println(t.Warning.Render(theme.IconWarning + " No [keys.shell.bindings] defined in grove.toml"))
		return nil
	}

	// Determine which shells to generate
	shells := []string{}
	if targetShell == "all" {
		shells = []string{"fish", "bash", "zsh"}
	} else {
		if _, ok := supportedShells[targetShell]; !ok {
			return fmt.Errorf("unsupported shell: %s (supported: fish, bash, zsh, all)", targetShell)
		}
		shells = []string{targetShell}
	}

	// Generate for each shell
	for _, shell := range shells {
		if err := generateShellConfig(shell, keysExt.Shell.Bindings, dryRun, t); err != nil {
			return err
		}
	}

	return nil
}

func generateShellConfig(shellName string, bindings map[string]string, dryRun bool, t *theme.Theme) error {
	shellCfg := supportedShells[shellName]

	// Build the configuration content
	var lines []string
	lines = append(lines, shellCfg.header()...)

	// Sort keys for consistent output
	var sortedKeys []string
	for k := range bindings {
		sortedKeys = append(sortedKeys, k)
	}
	sort.Strings(sortedKeys)

	for _, key := range sortedKeys {
		command := bindings[key]
		// Normalize the key first to ensure consistent format
		normalizedKey := keybind.Normalize(key, "grove")
		binding := shellCfg.formatBind(normalizedKey, command)
		lines = append(lines, binding)
	}

	lines = append(lines, shellCfg.footer()...)
	content := strings.Join(lines, "\n")

	// Determine output path
	outputPath := filepath.Join(paths.CacheDir(), shellName, fmt.Sprintf("grove-bindings.%s", shellCfg.ext))

	// Dry run: just print
	if dryRun {
		fmt.Println(t.Header.Render(fmt.Sprintf("%s Generated %s configuration:", theme.IconShell, shellName)))
		fmt.Println()
		fmt.Println(content)
		fmt.Println()
		return nil
	}

	// Create directory if needed
	outDir := filepath.Dir(outputPath)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", outDir, err)
	}

	// Write the file
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", outputPath, err)
	}

	fmt.Printf("%s Generated: %s (%d bindings)\n", t.Success.Render(theme.IconSuccess), outputPath, len(bindings))

	return nil
}

// printShellSourceInstructions prints instructions for sourcing generated configs.
func printShellSourceInstructions(t *theme.Theme) {
	fmt.Println()
	fmt.Println(t.Muted.Render("To use the generated keybindings, add to your shell config:"))
	fmt.Println()
	fmt.Println(t.Muted.Render("  Fish (~/.config/fish/config.fish):"))
	fmt.Printf("    %s\n", t.Code.Render(fmt.Sprintf("source %s/fish/grove-bindings.fish", paths.CacheDir())))
	fmt.Println()
	fmt.Println(t.Muted.Render("  Bash (~/.bashrc):"))
	fmt.Printf("    %s\n", t.Code.Render(fmt.Sprintf("source %s/bash/grove-bindings.bash", paths.CacheDir())))
	fmt.Println()
	fmt.Println(t.Muted.Render("  Zsh (~/.zshrc):"))
	fmt.Printf("    %s\n", t.Code.Render(fmt.Sprintf("source %s/zsh/grove-bindings.zsh", paths.CacheDir())))
}
