package cmd

// The docker satellite provider — local containers via the docker CLI, the
// second local exec-kind target after tart. Like tart there is no terraform
// and no bootstrap script; unlike tart there is no layer-0 auth bootstrap
// either: the image is grove-owned (an embedded Dockerfile + entrypoint,
// cmd/satelliteassets/targets/docker), so the container starts pubkey-ready —
// the per-satellite public key rides a read-only bind mount into the
// entrypoint, which installs it for the `grove` user before exec'ing sshd.
// The shared `up` verb then provisions the exec-kind satellite client-side
// from a locally cross-built stack (implied --prebuilt), with the cross
// target taken from the docker daemon's reported Os/Arch
// (DefaultPrebuiltTarget).
//
// Endpoint shape: sshd is published on a laptop-loopback port
// (127.0.0.1:<free-port> → container :22), so the endpoint/registry addr is
// 127.0.0.1:<port> and the shared verb keyscans/pins/ships against that
// mapped port. The -p mapping is part of the container's config and survives
// stop/start (docker persists HostConfig.PortBindings), and a restart `up`
// re-resolves it via `docker port` regardless, so a drifted assumption would
// surface immediately.
//
// Host keys are generated by the entrypoint's `ssh-keygen -A` on first start
// and persist in the container filesystem — the pinned host key is stable
// across stop/start and only rotates when the container is removed.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/grovetools/grove/cmd/satelliteassets"
)

// dockerSatelliteTarget is the infra target name the provider registers under.
const dockerSatelliteTarget = "docker"

// dockerGuestUser is the non-root login user the embedded Dockerfile creates
// (uid 1000, passwordless sudo for the grove-syncd system install step the
// shared prebuilt ship performs).
const dockerGuestUser = "grove"

// dockerImageRepo is the repository part of the grove-owned image tag; the
// tag part is a content hash of the embedded build context (see
// dockerSatelliteImageTag).
const dockerImageRepo = "grove-satellite"

// dockerAuthorizedKeysMount is where the provider bind-mounts the satellite's
// authorized_keys file (read-only) — the embedded entrypoint installs it from
// there. A mount rather than an env var keeps the key material out of
// `docker inspect`'s Env output.
const dockerAuthorizedKeysMount = "/run/grove/authorized_keys"

// dockerContainerName is the local container name for a satellite (same
// namespace prefix as tart's VMs).
func dockerContainerName(satName string) string { return "grove-sat-" + satName }

// dockerProviderRef is the provider_ref state value marking a container as
// grove-created for a given satellite ("docker:<container-name>").
func dockerProviderRef(container string) string { return dockerSatelliteTarget + ":" + container }

// dockerSatelliteProvider provisions local docker containers.
type dockerSatelliteProvider struct {
	target string
	// image is the resolved image reference, set by PrepareUp for Up.
	image string
	// imageIsOverride marks a BYO [satellites.<name>.infra] image: Up never
	// builds it, `docker create` pulls-or-fails with docker's own message.
	imageIsOverride bool
}

// newDockerSatelliteProvider is the registry constructor for the "docker"
// target.
func newDockerSatelliteProvider(target string) satelliteProvider {
	return &dockerSatelliteProvider{target: target}
}

func (p *dockerSatelliteProvider) Kind() string { return p.target }

// DefaultSatelliteKind: docker satellites are exec-only endpoints (sshd +
// grove binaries; no systemd in the container, so no groved/syncd stack).
func (p *dockerSatelliteProvider) DefaultSatelliteKind() string { return satelliteKindExec }

// UsesBootstrapScript: no — docker satellites are provisioned client-side
// (the shared verb's prebuilt path); the embedded image already contains the
// minimal guest prep the tart layer-0 bootstrap performs over ssh.
func (p *dockerSatelliteProvider) UsesBootstrapScript(_ string) bool { return false }

// DefaultPrebuiltTarget asks the docker daemon for its platform: containers
// run on the daemon's kernel/arch (Docker Desktop on Apple Silicon:
// linux/arm64; a linux amd64 host: linux/amd64), which is what the implied
// --prebuilt cross-build must produce.
func (p *dockerSatelliteProvider) DefaultPrebuiltTarget() (string, error) {
	out, err := exec.Command("docker", "version", "--format", "{{.Server.Os}}/{{.Server.Arch}}").Output()
	if err != nil {
		return "", fmt.Errorf("resolve the docker daemon's platform for the implied --prebuilt-target: %w (is the daemon running? start Docker Desktop or colima, or pass --prebuilt-target explicitly)%s", err, dockerExitStderr(err))
	}
	pair := strings.TrimSpace(string(out))
	parts := strings.Split(pair, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", fmt.Errorf("docker daemon platform %q is not <os>/<arch> — pass --prebuilt-target explicitly", pair)
	}
	return pair, nil
}

// PrepareUp validates the host environment (docker CLI on PATH, daemon
// reachable) and resolves the image reference. Read-only: the only docker
// invocation is `docker info`.
func (p *dockerSatelliteProvider) PrepareUp(opts *satelliteUpOptions) error {
	if _, err := exec.LookPath("docker"); err != nil {
		return fmt.Errorf("docker not found on PATH — install Docker Desktop (or colima and the docker CLI): %w", err)
	}
	if out, err := exec.Command("docker", "info", "--format", "{{.ServerVersion}}").CombinedOutput(); err != nil {
		return fmt.Errorf("docker daemon unreachable (`docker info` failed) — start Docker Desktop (or `colima start`) and retry: %s", strings.TrimSpace(string(out)))
	}
	if opts.Infra.Image != "" {
		p.image = opts.Infra.Image
		p.imageIsOverride = true
		return nil
	}
	files, err := satelliteassets.DockerBuildContext()
	if err != nil {
		return err
	}
	p.image = dockerSatelliteImageTag(files)
	return nil
}

// Up creates (or restarts) the satellite's local container and returns its
// endpoint. No billable-confirm prompt: a local container costs nothing to
// create and `down` removes it entirely (same stance as tart). Steps:
// key + authorized_keys → build-image-if-missing → `docker create` (stamp
// provider_ref) + `docker start`, or `docker start` of our stopped container
// → resolve the published port → wait for it → endpoint.
func (p *dockerSatelliteProvider) Up(ctx context.Context, opts *satelliteUpOptions) (satelliteEndpoint, error) {
	if p.image == "" {
		return satelliteEndpoint{}, fmt.Errorf("docker satellite provider: Up called without PrepareUp")
	}
	// Shared fail-fast work (the verb resolves nothing here for docker today,
	// but honor the contract).
	if opts.PostConfirm != nil {
		if err := opts.PostConfirm(); err != nil {
			return satelliteEndpoint{}, err
		}
	}

	container := dockerContainerName(opts.Name)

	// Dedicated per-satellite keypair + the authorized_keys file the
	// container bind-mounts. (Re)written on every up: a restart re-runs the
	// entrypoint, which reads the mount again — and a missing mount source
	// would make `docker start` materialize a directory in its place.
	keyPath, err := ensureDockerSatelliteKey(opts.Name)
	if err != nil {
		return satelliteEndpoint{}, err
	}
	akPath, err := writeDockerAuthorizedKeys(opts.Name, keyPath)
	if err != nil {
		return satelliteEndpoint{}, err
	}

	st, err := dockerContainerState(container)
	if err != nil {
		return satelliteEndpoint{}, err
	}
	if st.exists {
		// A container of our name already exists: restart it only when the
		// state file says WE created it for this satellite; otherwise it is a
		// collision with something else on the user's daemon (same policy as
		// tart).
		entries, serr := loadSatelliteState()
		if serr != nil || entries[opts.Name].ProviderRef != dockerProviderRef(container) {
			return satelliteEndpoint{}, fmt.Errorf(
				"docker container %q already exists but is not recorded as satellite %q's container in the grove state file — refusing to adopt it (remove it with `docker rm -f %s` or pick another satellite name)",
				container, opts.Name, container)
		}
		if st.running {
			fmt.Printf("Docker container %q is already running — reusing it.\n", container)
		} else {
			fmt.Printf("Restarting docker container %q...\n", container)
			if out, err := exec.Command("docker", "start", container).CombinedOutput(); err != nil {
				return satelliteEndpoint{}, fmt.Errorf("docker start %s: %w: %s", container, err, strings.TrimSpace(string(out)))
			}
		}
	} else {
		if err := p.ensureImage(); err != nil {
			return satelliteEndpoint{}, err
		}
		port, perr := pickFreeLocalhostPort()
		if perr != nil {
			return satelliteEndpoint{}, fmt.Errorf("pick a free local port for the container's sshd: %w", perr)
		}
		fmt.Printf("Creating docker container %q from %s (sshd published on 127.0.0.1:%d)...\n", container, p.image, port)
		if out, err := exec.Command("docker", dockerCreateArgs(container, port, akPath, p.image)...).CombinedOutput(); err != nil {
			return satelliteEndpoint{}, fmt.Errorf("docker create %s: %w: %s", container, err, strings.TrimSpace(string(out)))
		}
		// Stamp provider_ref into the state file the moment the container
		// exists (tart's partial-entry pattern from S2): if a later `up` step
		// fails (cross-build, ship), the re-run's ours-check above must still
		// recognize the container, and `down` must be able to find it. The
		// shared verb overwrites this partial entry with the full one on
		// success and removes it on `down`.
		if entries, serr := loadSatelliteState(); serr == nil {
			stamp := entries[opts.Name]
			stamp.ProviderRef = dockerProviderRef(container)
			stamp.Kind = satelliteKindExec
			if err := upsertSatelliteState(opts.Name, stamp); err != nil {
				fmt.Printf("warning: could not stamp the satellite state entry (a failed `up` re-run will not recognize the container as grove-created): %v\n", err)
			}
		}
		if out, err := exec.Command("docker", "start", container).CombinedOutput(); err != nil {
			return satelliteEndpoint{}, fmt.Errorf("docker start %s: %w: %s", container, err, strings.TrimSpace(string(out)))
		}
	}

	// Resolve the published port fresh on every up (create and restart both):
	// the fixed -p mapping survives restarts, but `docker port` is the truth.
	addr, err := dockerMappedSSHAddr(container)
	if err != nil {
		return satelliteEndpoint{}, err
	}
	// The published port accepts TCP as soon as docker's proxy listens; sshd
	// readiness inside the container is absorbed by the shared verb's
	// keyscan retries. This wait still catches a container that failed to
	// start at all (e.g. the entrypoint exiting over a missing key).
	if err := waitForTCPPort(ctx, addr, 2*time.Minute); err != nil {
		if ctx.Err() != nil {
			return satelliteEndpoint{}, err
		}
		return satelliteEndpoint{}, fmt.Errorf("docker container %q: %s never accepted a connection — did the container exit? (check `docker logs %s`): %w", container, addr, container, err)
	}

	return satelliteEndpoint{
		SSHAddr:      addr,
		User:         dockerGuestUser,
		IdentityFile: keyPath,
		ProviderRef:  dockerProviderRef(container),
	}, nil
}

// Down removes the container: destroy confirm, PostConfirm, `docker rm -f`,
// provider state-dir cleanup. Unlike tart there is no graceful
// sync-then-poweroff dance: `docker rm -f` (hard stop + remove) is safe here
// because a container has no VM disk whose unsynced guest page-cache writes
// could be lost — the container filesystem is deleted by the rm either way,
// and the satellite's durable artifacts (state entry, keys) live on the
// laptop. The built image is a shared cache and stays. State-entry removal
// stays the shared verb's job.
func (p *dockerSatelliteProvider) Down(_ context.Context, opts *satelliteDownOptions) error {
	if _, err := exec.LookPath("docker"); err != nil {
		return fmt.Errorf("docker not found on PATH — install Docker Desktop (or colima and the docker CLI): %w", err)
	}

	// The registry entry (config ∪ state) supplies the recorded container
	// name; fall back to the conventional name for a stateless cleanup run.
	entry, hasEntry := loadMergedSatellites()[opts.Name]
	container := dockerContainerName(opts.Name)
	if hasEntry && strings.HasPrefix(entry.ProviderRef, dockerSatelliteTarget+":") {
		container = strings.TrimPrefix(entry.ProviderRef, dockerSatelliteTarget+":")
	}

	if !opts.AssumeYes {
		if err := confirmOrAbort(fmt.Sprintf("Remove docker container %q and remove satellite %q's registry entry?", container, opts.Name)); err != nil {
			return err
		}
	}
	if opts.PostConfirm != nil {
		if err := opts.PostConfirm(); err != nil {
			return err
		}
	}

	st, err := dockerContainerState(container)
	if err != nil {
		return err
	}
	if !st.exists {
		fmt.Printf("(no docker container %q — nothing to remove; cleaning up provider files)\n", container)
	} else {
		if out, err := exec.Command("docker", "rm", "-f", container).CombinedOutput(); err != nil {
			return fmt.Errorf("docker rm -f %s: %w: %s", container, err, strings.TrimSpace(string(out)))
		}
		fmt.Printf("Docker container %q removed.\n", container)
	}

	// Provider-local files (dedicated key, authorized_keys). The image cache
	// is shared across satellites and stays.
	if dir, derr := dockerProviderDir(opts.Name); derr == nil {
		_ = os.RemoveAll(dir)
	}
	return nil
}

// --- docker CLI plumbing ---

// dockerProviderDir is the provider's slice of the per-satellite state dir
// (<StateDir>/satellites/<name>/docker): the dedicated ssh keypair and the
// bind-mounted authorized_keys file live here.
func dockerProviderDir(satName string) (string, error) {
	return satelliteProviderStateDir(satName, dockerSatelliteTarget)
}

// ensureDockerSatelliteKey generates (once) the satellite's dedicated ed25519
// keypair under the provider dir and returns the private key path.
func ensureDockerSatelliteKey(satName string) (string, error) {
	dir, err := dockerProviderDir(satName)
	if err != nil {
		return "", err
	}
	return ensureSatelliteProviderKey(dir, dockerContainerName(satName))
}

// writeDockerAuthorizedKeys (re)writes the authorized_keys file the container
// bind-mounts, from the satellite's public key. 0644: the container-side
// reader is the entrypoint (root) and the content is a public key.
func writeDockerAuthorizedKeys(satName, keyPath string) (string, error) {
	pub, err := os.ReadFile(keyPath + ".pub")
	if err != nil {
		return "", err
	}
	dir, err := dockerProviderDir(satName)
	if err != nil {
		return "", err
	}
	akPath := filepath.Join(dir, "authorized_keys")
	if err := writeFileAtomic(akPath, pub, 0o644); err != nil {
		return "", err
	}
	return akPath, nil
}

// dockerCreateArgs builds the `docker create` argv (pure; pinned by unit
// tests as the dry-run view of what Up executes). Restart policy stays the
// default "no" — a stopped container is restarted by a second `up` via
// `docker start`, mirroring tart's restart path. The authorized_keys ride a
// read-only bind mount (see dockerAuthorizedKeysMount).
func dockerCreateArgs(container string, port int, authorizedKeysPath, image string) []string {
	return []string{
		"create",
		"--name", container,
		"--restart", "no",
		"-p", fmt.Sprintf("127.0.0.1:%d:22", port),
		"-v", authorizedKeysPath + ":" + dockerAuthorizedKeysMount + ":ro",
		image,
	}
}

// dockerContainerStatus is the existence/running pair Up/Down branch on.
type dockerContainerStatus struct {
	exists  bool
	running bool
}

// dockerContainerState inspects one container by name. A missing container
// is not an error (exists=false); a daemon failure is.
func dockerContainerState(container string) (dockerContainerStatus, error) {
	out, err := exec.Command("docker", "container", "inspect", "--format", "{{.State.Running}}", container).Output() //nolint:gosec // G204: internal name
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			stderr := strings.ToLower(string(ee.Stderr))
			if strings.Contains(stderr, "no such container") || strings.Contains(stderr, "no such object") {
				return dockerContainerStatus{}, nil
			}
			return dockerContainerStatus{}, fmt.Errorf("docker container inspect %s: %w: %s", container, err, strings.TrimSpace(string(ee.Stderr)))
		}
		return dockerContainerStatus{}, fmt.Errorf("docker container inspect %s: %w", container, err)
	}
	return dockerContainerStatus{exists: true, running: strings.TrimSpace(string(out)) == "true"}, nil
}

// dockerListContainerStates returns name→running for every container the
// daemon knows about, in ONE `docker ps -a` — the status-time machine-state
// probe's batch counterpart to dockerContainerState's single-container inspect.
// ctx caps it so a hung daemon cannot stall status. Absent from the map = no
// such container (the probe reports that satellite "absent").
func dockerListContainerStates(ctx context.Context) (map[string]bool, error) {
	out, err := exec.CommandContext(ctx, "docker", "ps", "-a", "--format", "{{.Names}}\t{{.State}}").Output()
	if err != nil {
		return nil, fmt.Errorf("docker ps -a: %w%s", err, dockerExitStderr(err))
	}
	states := map[string]bool{}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line == "" {
			continue
		}
		// One container may map to multiple names (rare); the provider names
		// are unique, so the first tab splits name from the .State token
		// (running | exited | created | paused | ...).
		name, state, ok := strings.Cut(line, "\t")
		if !ok {
			continue
		}
		states[name] = state == "running"
	}
	return states, nil
}

// ensureImage makes p.image available locally: a present image is reused; a
// missing grove-owned image is built from the embedded context (streamed to
// the caller's terminal); a missing BYO override is left to `docker create`,
// which pulls-or-fails with docker's own registry messaging.
func (p *dockerSatelliteProvider) ensureImage() error {
	if err := exec.Command("docker", "image", "inspect", p.image).Run(); err == nil { //nolint:gosec // G204: internal/config tag
		return nil
	}
	if p.imageIsOverride {
		return nil
	}
	files, err := satelliteassets.DockerBuildContext()
	if err != nil {
		return err
	}
	ctxDir, err := os.MkdirTemp("", "grove-satellite-docker-ctx-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(ctxDir) }()
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(ctxDir, name), data, 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("Building satellite image %s from the embedded Dockerfile (one-time per asset change)...\n", p.image)
	if err := runInherited(ctxDir, "docker", "build", "-t", p.image, ctxDir); err != nil {
		return fmt.Errorf("docker build %s: %w", p.image, err)
	}
	return nil
}

// dockerMappedSSHAddr resolves the laptop-side address of the container's
// published :22 (e.g. "127.0.0.1:55007") via `docker port`.
func dockerMappedSSHAddr(container string) (string, error) {
	out, err := exec.Command("docker", "port", container, "22/tcp").Output() //nolint:gosec // G204: internal name
	if err != nil {
		return "", fmt.Errorf("docker port %s 22/tcp: %w%s", container, err, dockerExitStderr(err))
	}
	// First line only: an ipv6 binding would list a second line, but the
	// provider always publishes on 127.0.0.1.
	line := strings.TrimSpace(strings.SplitN(strings.TrimSpace(string(out)), "\n", 2)[0])
	if _, _, err := net.SplitHostPort(line); err != nil {
		return "", fmt.Errorf("docker port %s 22/tcp returned %q, not host:port — is :22 published?", container, line)
	}
	return line, nil
}

// dockerExitStderr renders an exec.ExitError's captured stderr as an error
// suffix (": <stderr>"), empty otherwise.
func dockerExitStderr(err error) string {
	if ee, ok := err.(*exec.ExitError); ok && len(ee.Stderr) > 0 {
		return ": " + strings.TrimSpace(string(ee.Stderr))
	}
	return ""
}

// dockerSatelliteImageTag derives the grove-owned image tag from the embedded
// build-context content: grove-satellite:<first 12 hex of a sha256 over the
// sorted files>. Editing the Dockerfile/entrypoint changes the tag, so the
// next `up` rebuilds naturally; unchanged assets reuse the cached image.
func dockerSatelliteImageTag(files map[string][]byte) string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	h := sha256.New()
	for _, name := range names {
		h.Write([]byte(name))
		h.Write([]byte{0})
		h.Write(files[name])
		h.Write([]byte{0})
	}
	return dockerImageRepo + ":" + hex.EncodeToString(h.Sum(nil))[:12]
}
