package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/grovetools/core/config"
)

// syncTestDir builds a scratch config dir with a sync.token present (the
// state bootstrap step 7 leaves behind). All laptop sync tests operate on
// scratch dirs — never the user's real ~/.config/grove.
func syncTestDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, syncTokenFileName), []byte("tok-abc\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return dir
}

// TestLaptopSyncConfigCreate covers the create-from-scratch path: golden
// content shape, loadable through core's real sync loader, and — the hard
// invariant — no pull key anywhere.
func TestLaptopSyncConfigCreate(t *testing.T) {
	dir := syncTestDir(t)
	var out strings.Builder
	if err := setupLaptopSyncConfig(dir, 8788, []string{"cloud", "grovetools"}, &out); err != nil {
		t.Fatalf("setupLaptopSyncConfig: %v", err)
	}

	syncPath := filepath.Join(dir, syncConfigFileName)
	data, err := os.ReadFile(syncPath)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)

	for _, want := range []string{
		"generated by `grove satellite up`",
		"PUSH-ONLY",
		`server = "http://127.0.0.1:8788"`,
		`token_command = "cat ` + filepath.Join(dir, syncTokenFileName) + `"`,
		"[[workspaces]]",
		`name = "cloud"`,
		`name = "grovetools"`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("created sync.toml missing %q:\n%s", want, text)
		}
	}
	// HARD INVARIANT: never a pull key in a generated laptop config. The
	// header comment mentions "pull = true" prose, so check config lines only.
	assertNoPullConfigured(t, syncPath)

	// The real loader must accept it and see exactly the push-only entries.
	cfg, err := config.LoadSyncConfigFrom(syncPath)
	if err != nil {
		t.Fatalf("LoadSyncConfigFrom: %v", err)
	}
	if cfg == nil || len(cfg.Workspaces) != 2 {
		t.Fatalf("loaded sync config = %+v, want 2 workspaces", cfg)
	}
	for i, name := range []string{"cloud", "grovetools"} {
		if cfg.Workspaces[i].Name != name || cfg.Workspaces[i].Pull {
			t.Fatalf("workspace[%d] = %+v, want push-only %q", i, cfg.Workspaces[i], name)
		}
	}
	if cfg.Server != "http://127.0.0.1:8788" {
		t.Fatalf("server = %q", cfg.Server)
	}
}

// assertNoPullConfigured parses the file through the canonical schema and
// fails if any workspace entry is pull-enabled, and additionally greps the
// non-comment lines for a literal pull key.
func assertNoPullConfigured(t *testing.T, path string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(trimmed, "pull") {
			t.Fatalf("laptop sync config contains a pull key (PUSH-ONLY invariant broken): %q", line)
		}
	}
	cfg, err := config.LoadSyncConfigFrom(path)
	if err != nil {
		t.Fatalf("LoadSyncConfigFrom: %v", err)
	}
	for _, ws := range cfg.Workspaces {
		if ws.Pull {
			t.Fatalf("workspace %q is pull-enabled (PUSH-ONLY invariant broken)", ws.Name)
		}
	}
}

// TestLaptopSyncTokenMissing: the finishing step hard-errors (with
// remediation) when bootstrap's fetched token is absent, and writes nothing.
func TestLaptopSyncTokenMissing(t *testing.T) {
	dir := t.TempDir() // no sync.token
	var out strings.Builder
	err := setupLaptopSyncConfig(dir, 8788, []string{"cloud"}, &out)
	if err == nil {
		t.Fatal("expected an error when sync.token is missing")
	}
	for _, want := range []string{filepath.Join(dir, syncTokenFileName), "remediation", "token create laptop"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("token-missing error lacks %q: %v", want, err)
		}
	}
	if _, statErr := os.Stat(filepath.Join(dir, syncConfigFileName)); !os.IsNotExist(statErr) {
		t.Fatal("sync.toml must not be written when the token is missing")
	}
}

// TestLaptopSyncConfigMerge covers the append-only merge: comments and
// existing entries preserved byte-for-byte (old content stays a prefix), only
// missing workspaces appended, and no pull key emitted.
func TestLaptopSyncConfigMerge(t *testing.T) {
	dir := syncTestDir(t)
	syncPath := filepath.Join(dir, syncConfigFileName)
	original := `# my hand-written sync config — precious comment
server = "http://127.0.0.1:8788"
token_command = "cat ~/.config/grove/sync.token"

[[workspaces]]
name = "cloud"
mode = "plans-only" # hand-tuned; must never be edited
`
	if err := os.WriteFile(syncPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	if err := setupLaptopSyncConfig(dir, 8788, []string{"cloud", "grovetools"}, &out); err != nil {
		t.Fatalf("setupLaptopSyncConfig (merge): %v", err)
	}

	data, err := os.ReadFile(syncPath)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)

	// Append-only: the previous file survives as an exact byte prefix.
	if !strings.HasPrefix(text, original) {
		t.Fatalf("merge edited existing content (old file is not a byte prefix):\n%s", text)
	}
	if !strings.Contains(text, `name = "grovetools"`) {
		t.Fatalf("missing workspace was not appended:\n%s", text)
	}
	if n := strings.Count(text, `name = "cloud"`); n != 1 {
		t.Fatalf("existing entry duplicated (%d occurrences):\n%s", n, text)
	}
	assertNoPullConfigured(t, syncPath)

	cfg, err := config.LoadSyncConfigFrom(syncPath)
	if err != nil {
		t.Fatalf("merged config unreadable by real loader: %v", err)
	}
	if len(cfg.Workspaces) != 2 || cfg.Workspaces[0].Mode != "plans-only" {
		t.Fatalf("merged workspaces = %+v", cfg.Workspaces)
	}

	// A port mismatch was not present → no warning.
	if strings.Contains(out.String(), "warning") {
		t.Fatalf("unexpected warning: %s", out.String())
	}

	// Idempotence: a second run changes nothing.
	if err := setupLaptopSyncConfig(dir, 8788, []string{"cloud", "grovetools"}, &out); err != nil {
		t.Fatalf("second merge: %v", err)
	}
	again, _ := os.ReadFile(syncPath)
	if string(again) != text {
		t.Fatalf("second merge modified the file:\n%s", string(again))
	}
}

// TestLaptopSyncConfigMergePortMismatch: a server on a different port draws a
// warning and the server line is NOT changed.
func TestLaptopSyncConfigMergePortMismatch(t *testing.T) {
	dir := syncTestDir(t)
	syncPath := filepath.Join(dir, syncConfigFileName)
	original := `server = "http://127.0.0.1:9999"

[[workspaces]]
name = "cloud"
`
	if err := os.WriteFile(syncPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	if err := setupLaptopSyncConfig(dir, 8788, []string{"cloud", "grovetools"}, &out); err != nil {
		t.Fatalf("setupLaptopSyncConfig: %v", err)
	}
	if !strings.Contains(out.String(), "warning") || !strings.Contains(out.String(), "9999") {
		t.Fatalf("expected a port-mismatch warning, got: %s", out.String())
	}
	data, _ := os.ReadFile(syncPath)
	if !strings.Contains(string(data), `server = "http://127.0.0.1:9999"`) {
		t.Fatalf("server line was modified:\n%s", data)
	}
	if !strings.HasPrefix(string(data), original) {
		t.Fatalf("merge edited existing content:\n%s", data)
	}
}

// TestLaptopSyncConfigMergePreservesUserPullEntry: an existing (user-authored)
// pull entry is warned about but never edited — the merge path must not touch
// existing entries even when they violate the push-only convention.
func TestLaptopSyncConfigMergePreservesUserPullEntry(t *testing.T) {
	dir := syncTestDir(t)
	syncPath := filepath.Join(dir, syncConfigFileName)
	original := `server = "http://127.0.0.1:8788"

[[workspaces]]
name = "cloud"
pull = true
`
	if err := os.WriteFile(syncPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	var out strings.Builder
	if err := setupLaptopSyncConfig(dir, 8788, []string{"cloud", "grovetools"}, &out); err != nil {
		t.Fatalf("setupLaptopSyncConfig: %v", err)
	}
	if !strings.Contains(out.String(), "PUSH-ONLY") {
		t.Fatalf("expected a push-only warning about the existing pull entry, got: %s", out.String())
	}
	data, _ := os.ReadFile(syncPath)
	if !strings.HasPrefix(string(data), original) {
		t.Fatalf("merge edited the user's pull entry:\n%s", data)
	}
	// The appended entry itself must be push-only.
	appended := strings.TrimPrefix(string(data), original)
	if strings.Contains(appended, "pull") {
		t.Fatalf("appended region contains a pull key:\n%s", appended)
	}
}

// TestRenderLaptopSyncWorkspacesRefusesPull pins the hard invariant at its
// enforcement point: the renderer errors on any pull-enabled entry.
func TestRenderLaptopSyncWorkspacesRefusesPull(t *testing.T) {
	if _, err := renderLaptopSyncWorkspaces([]laptopSyncWorkspace{{Name: "cloud", Pull: true}}); err == nil {
		t.Fatal("renderer must refuse pull = true for a laptop workspace entry")
	} else if !strings.Contains(err.Error(), "PUSH-ONLY") {
		t.Fatalf("refusal should explain the push-only invariant: %v", err)
	}
	if _, err := renderLaptopSyncWorkspaces([]laptopSyncWorkspace{{Name: ""}}); err == nil {
		t.Fatal("renderer must refuse an empty workspace name")
	}
	// Happy path renders name-only entries.
	got, err := renderLaptopSyncWorkspaces(laptopSyncEntries([]string{"cloud"}))
	if err != nil {
		t.Fatal(err)
	}
	if got != "\n[[workspaces]]\nname = \"cloud\"\n" {
		t.Fatalf("rendered entry = %q", got)
	}
}

// TestSatelliteRegistrySyncFields covers the registry surface post-split: the
// sync_local_port/sync_remote_addr fields round-trip through the STATE file
// (grove.toml keeps only the hand-written .provision/.sync subtables and is
// never touched), the merged view carries the sync fields, and the
// [satellites.<name>.sync] block still parses grove-side.
func TestSatelliteRegistrySyncFields(t *testing.T) {
	configDir := setupGroveHome(t)
	tomlPath := filepath.Join(configDir, "grove.toml")
	original := `# hand-written config
[satellites.sat1.provision]
gh_token_cmd = "gh auth token"

[satellites.sat1.sync]
workspaces = ["cloud", "grovetools", "extra"]
`
	if err := os.WriteFile(tomlPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	entry := satelliteConfigEntry{
		SSHAddr:        "203.0.113.7:22",
		User:           "solair",
		HostKey:        "ssh-ed25519 AAAA",
		SyncLocalPort:  8788,
		SyncRemoteAddr: "127.0.0.1:8788",
	}
	if err := upsertSatelliteState("sat1", entry); err != nil {
		t.Fatalf("upsertSatelliteState: %v", err)
	}

	// grove.toml stays byte-for-byte; the sync fields live in state only.
	data, err := os.ReadFile(tomlPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != original {
		t.Errorf("state upsert modified grove.toml:\n%s", data)
	}

	// Merged view (what the daemon's LoadRegistry and the CLI readers see):
	// the state-only entry passes through complete, sync fields included,
	// alongside the subtable-only config side — with no drift warning.
	merged, warnings := mergeSatelliteEntries(loadSatellitesViaConfig(t), mustLoadSatelliteState(t))
	if got := merged["sat1"]; got != entry {
		t.Fatalf("merged entry = %+v, want %+v", got, entry)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected merge warnings: %v", warnings)
	}

	// Grove-side [satellites.<name>.sync] parse.
	cfg, err := config.LoadFrom(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	opts, err := satelliteSyncOptionsFromConfig(cfg, "sat1")
	if err != nil {
		t.Fatalf("satelliteSyncOptionsFromConfig: %v", err)
	}
	if strings.Join(opts.Workspaces, ",") != "cloud,grovetools,extra" {
		t.Fatalf("sync workspaces = %v", opts.Workspaces)
	}

	// Upsert (re-provision) replaces the state entry in place.
	entry.SyncLocalPort = 9000
	if err := upsertSatelliteState("sat1", entry); err != nil {
		t.Fatal(err)
	}
	state := mustLoadSatelliteState(t)
	if len(state) != 1 || state["sat1"].SyncLocalPort != 9000 {
		t.Fatalf("upserted state = %+v", state)
	}
}

// TestResolveSatelliteSyncWorkspacesPrecedence pins flag > config > default,
// including the set-to-empty disable.
func TestResolveSatelliteSyncWorkspacesPrecedence(t *testing.T) {
	cfg := satelliteSyncOptions{Workspaces: []string{"alpha", "beta"}}

	// Flag set → flag wins (whitespace and empty segments tolerated).
	if got := resolveSatelliteSyncWorkspaces(cfg, " x , y ,", true); strings.Join(got, ",") != "x,y" {
		t.Fatalf("flag-set resolve = %v", got)
	}
	// Flag set to empty → explicit disable (no workspaces).
	if got := resolveSatelliteSyncWorkspaces(cfg, "", true); len(got) != 0 {
		t.Fatalf("set-to-empty flag should disable workspaces, got %v", got)
	}
	// Flag unset → config block wins.
	if got := resolveSatelliteSyncWorkspaces(cfg, "ignored", false); strings.Join(got, ",") != "alpha,beta" {
		t.Fatalf("config resolve = %v", got)
	}
	// Neither → compat default pair.
	if got := resolveSatelliteSyncWorkspaces(satelliteSyncOptions{}, "", false); strings.Join(got, ",") != strings.Join(defaultSatelliteSyncWorkspaces, ",") {
		t.Fatalf("default resolve = %v", got)
	}
}
